### ISSUE TITLE
Support relative path for ES information

### ISSUE THREAD

**Issue by matthughes** [lmenezes/elasticsearch-kopf#153]
Kibana has a config.js file that let's you specify where  your ES instance is running.  In my case, I have nginx in front of ES and am trying to open up only certain paths to certain users.  My goal is to be able to host kopf at:

https://host/admin/

I succesfully have all the static assets being returned; I just do redirect so that /admin/ turns into /_plugin/kopf/ on the ES machine.  However, Kopf expects ES API to start at /, but I really want it to start at /es/.  Is this possible?

Better yet would be if I could run Kopf in my local browser and just point to a remote instance, but I feel like CORS stuff is going to prevent that.

**Comment by MarkMurphy** [comment]
so...how do I make use of this? Some documentation would be nice.

**Comment by matthughes** [comment]
@MarkMurphy Something like this:


Edit kopf_external_settings.json:

```
{
    "elasticsearch_root_path": "/adminaccess/",
}
```

Then, in your web server proxy (nginx, apache) perform redirect.  This example is with Apache:

```
  <Location /adminaccess/>
      ProxyPass http://127.0.0.1:9200/
  </Location>
```

Your user can now go to http://elk_server/adminaccess/ and reach kopf.
