### ISSUE TITLE
Cannot have query response pretty print when running KOPF on windows

### ISSUE THREAD

**Issue by dan-s1** [lmenezes/elasticsearch-kopf#158]
I am accessing KOPF in a Firefox browser on a Windows box and a Windows VM yet
the query response does not pretty print even if I specify ?pretty in the request URL. 
The response does pretty print when I access KOPF in Firefox on a Linux VM.

**Comment by lmenezes** [comment]
@dan-s1 I'm dropping further development for kopf, and this will be mostly updated only for compatibility issues with newer ES versions or bugs found along the way. So, unfortunately there won't be any progress on this issue.
