### ISSUE TITLE
Show node uptime in cluster overview view

### ISSUE THREAD

**Issue by captSL** [lmenezes/elasticsearch-kopf#181]
It would be nice to see the uptime of each cluster node in the cluster overview, maybe next to the docs and size values.

**Comment by lmenezes** [comment]
not exactly what you wanted... but hope it's good enough :)
![uptime](https://cloud.githubusercontent.com/assets/750074/6716642/23623490-cda7-11e4-85c4-5d44b0c03b33.png)
