### ISSUE TITLE
Associate themes to hosts

### ISSUE THREAD

**Issue by moliware** [lmenezes/elasticsearch-kopf#182]
Hi!

After having #171 it would great to associate themes to hosts, so that I can use a different theme for a production cluster for example.

If you think it's useful for the project I can develop and send you a PR :)

Thanks!

**Comment by geekpete** [comment]
Or more accurately associate theme to cluster name.

If you hit different search hosts on the same cluster, it should know that the theme belongs to that specific cluster.

It's an important distinction.

Should be able to be saved in a cookie.

**Comment by lmenezes** [comment]
I won't be working on this on kopf, but perhaps I will do so for https://github.com/lmenezes/cerebro :)
