### ISSUE TITLE
Colour for heap usage missleading

### ISSUE THREAD

**Issue by robin13** [lmenezes/elasticsearch-kopf#187]
I'm not sure if this is a bug, or I'm misunderstanding what it means...  Here's an example I often see:
![2014-10-24 07_56_36-kopf](https://cloud.githubusercontent.com/assets/174291/4765709/026f3994-5b43-11e4-9d70-5d803be0d78b.png)
es105 is showing red, but is at 6.35 of 12GB, while es103 is at 6.82 of 12GB.
I assumed that blue == ok, and red == over some percentage of the total, i.e. warning.
Is this a bug, or do the bars mean something different?
Could I have found this explained in documentation somewhere?
Using kopf v1.3.4

Thanks!

**Comment by pires** [comment]
+1
