### ISSUE TITLE
index navigation improvement for cluster which has so many indeies

### ISSUE THREAD

**Issue by jeesim2** [lmenezes/elasticsearch-kopf#220]
I have about 100 indicies and it is a little tired to navigate between indicies.
It would be great if index navigation got some improvements.
to my bad english I'd like to suggest by image! :) :D
![2014-12-24 09 15 22](https://cloud.githubusercontent.com/assets/1100831/5544613/f8581b1a-8b4e-11e4-8aa3-835f2fde6633.PNG)

**Comment by lmenezes** [comment]
@jeesim2 hey, just published v1.4.5

I added the option to sort indices asc/desc, and you can now paginate indices using left and right arrows.

**Comment by jeesim2** [comment]
wow. that's awesome!!! I'll try it on!!

**Comment by jeesim2** [comment]
btw, each node's cpu and disk usage indicator has gone.
it was very useful information to me. what happen? or some issued problem?

**Comment by lmenezes** [comment]
@jeesim2 yes, I have removed them and added a new "nodes" section. I'm not sure about your particular use case, but I assume if you use kopf for monitoring your nodes, the nodes section might give you more insight(it's still being improved). does it make sense?

**Comment by jeesim2** [comment]
@lmenezes 
I usually use kopf main cluster view for monitoring purpose(cpu, heap, disk. they were great) in general.

but I'm expecting your next release and improving about monitoring feature.

ThankS!!!
my favorite ES site plugin.!!!
