### ISSUE TITLE
the plugin doesn't work with Elasticsearch version 1.3.4

### ISSUE THREAD

**Issue by sushanthku** [lmenezes/elasticsearch-kopf#222]
![image](https://cloud.githubusercontent.com/assets/1033383/5750621/44aa7972-9c0c-11e4-873a-e0c35925e261.png)
)
The plugin UI errors out with the message "Error refreshing cluster state". I am running ES version 1.3.4 and kopf 1.4.3

**Comment by lmenezes** [comment]
could you copy/paste any output from your browser console?

As far as I have tested, it does work with elasticsearch 1.3.4.

Also, what is your setup? How many nodes? Are you using elasticsearch behind some kind of proxy?

**Comment by sushanthku** [comment]
Here's the output of console in debug mode: 
```
GET http://hostaddress:9200/_plugin/kopf/dist/%7B%7BgetTheme()%7D%7D_style.css 404 (Not Found) hostaddress/:12
Resource interpreted as Font but transferred with MIME type application/octet-stream: "http://hostaddress:9200/_plugin/kopf/font-awesome/fonts/fontawesome-webfont.woff?v=4.2.0".
Requesting cluster information with params: kopf.js:3517
Object {} kopf.js:3517
Requesting [hostaddress:9200] with params: kopf.js:3517
Object {method: "GET", url: "hostaddress:9200/_cluster/health", data: Object}
 kopf.js:3517
Requesting cluster information with params: kopf.js:3517
Object {} kopf.js:3517
Requesting [hostaddress:9200] with params: kopf.js:3517
Object {method: "GET", url: "hostaddress:9200/_cluster/health", data: Object}
 kopf.js:3517
Requesting cluster information with params: kopf.js:3517
Object {} kopf.js:3517
Requesting [hostaddress:9200] with params: 
```

**Comment by sushanthku** [comment]
No proxy. I have about 32 nodes.   The plugin did work with version 1.0.0 earlier.

**Comment by lmenezes** [comment]
Could you also share the response of the REST calls?

Somebody reported something like that before, but it was a problem with the cluster(actually, the plugin worked from some nodes and didn't from others). After upgrading, the cluster was in a weird state where some nodes were not seen by other nodes and etc.

I will anyway later today release a new version of kopf, and will add some more debug lines that could help shed a light of what is going on.

**Comment by sushanthku** [comment]
Did the problem get fixed for that guy with a restart?  I dont see anything unusual in the rest responses. 
which REST call response do you want to see?

**Comment by lmenezes** [comment]
@sushanthku sorry for the delay. actually if I could get all responses, that would be perfect(you can of course, hide any important information such as hosts and so on). This way I can just run locally your content and see exactly what is failing.

**Comment by lmenezes** [comment]
@sushanthku did anything change on this?

**Comment by sushanthku** [comment]
I see the data for aliases and nodes in the console debugger. But the UI
still errors out. I did a restart of the cluster but still no luck.

-Sushanth

On Wed, Mar 18, 2015 at 10:22 AM, leonardo menezes <notifications@github.com
> wrote:

> @sushanthku <https://github.com/sushanthku> did anything change on this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lmenezes/elasticsearch-kopf/issues/222#issuecomment-83066712>
> .
>



-- 
-Sushanth

**Comment by sushanthku** [comment]
This is the error we see:

GET http://abc.com:9200/_plugin/kopf/dist/%7B%7BgetTheme()%7D%7D_style.css
404 (Not Found) abc.com/:12
Resource interpreted as Font but transferred with MIME type
application/octet-stream: "
http://abc.com:9200/_plugin/kopf/font-awesome/fonts/fontawesome-webfont.woff?v=4.2.0
".


On Fri, Mar 20, 2015 at 3:08 PM, sushanth kumar <sushanthku@gmail.com>
wrote:

> I see the data for aliases and nodes in the console debugger. But the UI
> still errors out. I did a restart of the cluster but still no luck.
>
> -Sushanth
>
> On Wed, Mar 18, 2015 at 10:22 AM, leonardo menezes <
> notifications@github.com> wrote:
>
>> @sushanthku <https://github.com/sushanthku> did anything change on this?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/lmenezes/elasticsearch-kopf/issues/222#issuecomment-83066712>
>> .
>>
>
>
>
> --
> -Sushanth
>



-- 
-Sushanth

**Comment by lmenezes** [comment]
@sushanthku hey, I have just released a new version(v1.5.0). I don't expect this to fix your problem, but I have added a logging section which should help me figure out what is going wrong.
If you still have that issue, just copy and paste whatever is on the log and then I will try to figure out what is wrong :)
![screenshot 2015-04-20 23 00 33](https://cloud.githubusercontent.com/assets/750074/7240442/42a942c0-e7b1-11e4-9a21-7e7a51d1e295.png)

**Comment by lmenezes** [comment]
@sushanthku any update on this?

**Comment by lmenezes** [comment]
@sushanthku i will close this issue for now, feel free to open another one if you still have problems
