### ISSUE TITLE
Duplicated indices in cluster overview

### ISSUE THREAD

**Issue by kroepke** [lmenezes/elasticsearch-kopf#223]
Running ES 1.4.2 with kopf 1.4.3 I see two entries for every index in my single node cluster:
![screenshot](https://cloud.githubusercontent.com/assets/52014/5757877/077622c2-9cc0-11e4-86cf-461e2ee8e58c.png)

I've tracked it down to https://github.com/lmenezes/elasticsearch-kopf/blob/master/src/kopf/elastic/cluster.js#L62 which will add indices for which cluster blocks are present.
Should that still be in there? Or rather, should it try to see if it doesn't have any existing index before pushing it?

**Comment by lmenezes** [comment]
hum, this is funny. It also shows the index as closed, right? 

i will have to take a look if something changed recently(I'm running 1.4.1, so could have happened in 1.4.2?).

Can you reproduce this issue in an empty cluster, by just creating a new index?

**Comment by kroepke** [comment]
This also happened in 1.4.1. I'll make a new cluster and report back.

**Comment by lmenezes** [comment]
hum... funny. I'm running 1.4.1 currently, and looks good here. Are you also using most recent version of kopf?

**Comment by lmenezes** [comment]
and if you can gist the output of your _state rest all, would be awesome.

The piece of code you mention, adds a "closed" index whenever the index is reported as blocked. Maybe it's also blocked for some other reason(apart from being closed) and I'd have to treat that as well?

**Comment by kroepke** [comment]
yes. This doesn't happen with a simple create index. Apparently we have blocks on that index. We do set indices to read only, which I just tried on the new cluster: Index is duplicated.
I'll attach the _state in a separate post.
To reproduce: create one index, edit settings -> blocks -> read_only = true, duplicate index is shown.

**Comment by kroepke** [comment]
https://gist.github.com/anonymous/5e67d2294a638efe06e7

**Comment by lmenezes** [comment]
http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/cluster-update-settings.html#_metadata

Yep, that must be it. I will have to then check if the index is really closed. I recently changed a lot of the code so that I dont have to request so much data, and on the way I must have taken a few wrong shortcuts, like this one ;)

Will take a look and see how I can fix that! thanks for reporting ;)

**Comment by kroepke** [comment]
cool, thanks!

**Comment by lmenezes** [comment]
:beer: friday?

**Comment by lmenezes** [comment]
aka tomorrow?

**Comment by lmenezes** [comment]
```
"blocks": {
        "indices": {
            "bar": {
                "4": {
                    "description": "index closed",
                    "retryable": false,
                    "levels": [
                        "read",
                        "write"
                    ]
                }
            },
            "foo": {
                "7": {
                    "description": "index read (api)",
                    "retryable": false,
                    "levels": [
                        "read"
                    ]
                }
            }
        }
    }
```

For now I guess I can just check the "description" for ensuring the index is actually closed. Will try to have it done later :)

**Comment by kroepke** [comment]
The keys in that structure correspond to the description, that might be easier. Compare org.elasticsearch.cluster.metadata.IndexMetaData#INDEX_READ_ONLY_BLOCK etc in elasticsearch.

Could happen with the beers, let's talk tomorrow :)

**Comment by lmenezes** [comment]
aha, right! checking for 4 is way easier!

as for the beers, we got a lot to catch up... plus, Saturday is my birthday.

**Comment by kroepke** [comment]
woot another year gone by!

**Comment by lmenezes** [comment]
@kroepke v1.4.4 :)

**Comment by kroepke** [comment]
Yay!! Thanks!
