### ISSUE TITLE
query console/formatter throws "Bad String error" When I use single quotes instead of double quotes..

### ISSUE THREAD

**Issue by syllogismos** [lmenezes/elasticsearch-kopf#224]
Hands down my favorite elasticsearch extension. Thank you. :)

When I copy paste queries from python interpreter or somewhere else, I will have to change all single quotes into double quotes.. Just a slight inconvenience.

I don't know if there is a reason for only allowing double quotes..

**Comment by lmenezes** [comment]
@syllogismos as far as I know, the JSON spec only allows double quotes for strings(not like python, ruby...). 

So, it's really just not valid JSON. If kopf actually allowed you to send the request, you would still get:
```
JsonParseException[Unexpected character (''' (code 39))
```

It's possible to get a valid JSON string from python though.
