### ISSUE TITLE
this.load_average is undefined

### ISSUE THREAD

**Issue by lchane** [lmenezes/elasticsearch-kopf#228]
Hi,

I have an issue with the latest snapshot of kopf that prevents loading the dashboard.

Somewhere in the code (breakpoint with firebug):

this.load_average = getProperty(this.stats, 'os.load_average');
this.minuteAverage = this.load_average[0];

TypeError: this.load_average is undefined

It works fine with 1.4.4

Thanks for you help,
Laurent

**Comment by lmenezes** [comment]
@lchane do you have the most recent snapshot?

**Comment by lchane** [comment]
I usually use http://lmenezes.com/elasticsearch-kopf/?location=.....
So I'm not sure which version this is.

I also forced a reload, just in case.

**Comment by lmenezes** [comment]
ok.. and which version of elasticsearch? 
Also, when you start your node, do you get any warn/error messages?

This is the most up to date snapshot, but it is also the one that I use daily(it helps me find bugs), and currently for me it's working fine.

**Comment by lchane** [comment]
elasticsearch 1.4.2
logstash 1.4.2
on Debian.

logstash.err is empty on all nodes.

In the browser, I get a red pop up every 5 sec stating:
Error refreshing cluster state
{}

Getting the JSON data from EL seems ok:
GET http://xxx:9200/_cluster/state/master_node,nodes,routing_table,blocks/
200 OK

GET http://xxx:9200/_status
200 OK

GET http://xxx:9200/_nodes/stats/jvm,fs,os
200 OK

GET http://xxx:9200/_cluster/settings
200 OK

GET http://xxx:9200/_aliases	
200 OK

GET http://xxx:9200/_cluster/health	
200 OK

Not sure what else to look for

**Comment by lchane** [comment]
the JSON returned by /_nodes/stats/jvm,fs,os
contains for each node only os.timestamp (for the os part)

Maybe it's a logstash config somewhere to include load_average?

**Comment by lmenezes** [comment]
@lchane what I think might be happening, is that sigar is not being loaded correctly(for whatever reason), and I remember seeing something like that before.

I will anyway handle the case where this is not available. A fix should be ready in a few minutes.

**Comment by lmenezes** [comment]
pushed. care to take a look and make sure it works? :)

**Comment by lchane** [comment]
Perfect. The updated interface is nice too.

Sigar is indeed installed on the elasticsearch node, but not on the logstash node. I'll see how to do this.

Thanks for your support,
Laurent

**Comment by lmenezes** [comment]
@lchane cool, glad you liked it :)
