### ISSUE TITLE
How KOPF makes the connection to the ElasticSearch

### ISSUE THREAD

**Issue by kamburi** [lmenezes/elasticsearch-kopf#229]
Hi All,

I couldn´t find in the document an explanation on how KOPF does the connection to the ElasticSearch.

If I run KOPF as default, it connects perfectly to the ElasticSearch (HTTP and port 9200), but if I do over HTTPS, things are not that easy...

I wanted to know how is the connection made, because I´ve configured my NGINX with a proxy_pass to http://127.0.0.1:9200 and everything it says that the connection couldn´t be made, but Kibana connects without any problem. So what´s the magic?

My KOPF listens at https://hostname/kopf. The UI opens but the connection cannot be made.
Please, is there a diagram? Draft somewhere? Or how can I enable debug on KOPF so I can see every moment of the connection being made?

Thank you in advance.

**Comment by lmenezes** [comment]
@kamburi sorry for the delay, a bit busy lately. Does this thread helps you at all? https://github.com/lmenezes/elasticsearch-kopf/issues/153
Need to find time to update readme with instructions on how to get this working :)

**Comment by smcquilling** [comment]
I have a similar issue, however, i am reverse proxying from another host with nginx. nginx is on serverA (running https://) and elasticsearch and kopf are on serverB. I open my broswer and navigate to https://serverA/kopf. I get to the main KOPF page fine, but kopf throws a  "Error connecting to [https://serverA:443]", when it should be going http://serverB:9200

Is there a config setting on the kopf side i am missing?

In nginx.conf:
  location /kopf/ {
    proxy_pass http://serverB:9200/_plugin/kopf/;
    proxy_read_timeout 90;
  }

**Comment by cwhits** [comment]
I'm having the same issue as @smcquilling :(

**Comment by lmenezes** [comment]
@cwhits does this helps you https://github.com/lmenezes/elasticsearch-kopf/issues/153 ?

**Comment by cwhits** [comment]
@lmenezes it looks like that's only helpful when I'm changing the ES root path on the server kopf/elasticsearch are running on. I'm attempting to proxy from a server not running ES or kopf so I can proxy into it without opening it up to anything/anyone. 

I want to connect to https://serverA/kopf and have it proxy to http://serverB:9200/_plugin/kopf 

The proxy works fine but then kopf says it can't connect to ES at https://serverA:443/

If I use "elasticsearch_root_path": "http://serverB:9200/" I just get "no connection"

**Comment by lmenezes** [comment]
@kamburi @smcquilling @cwhits I have just released a new version(v1.5.0) which adds a log at the bottom of the screen.
If you could copy + paste the output of it, maybe I can figure out what is wrong :)
![screenshot 2015-04-20 23 00 33](https://cloud.githubusercontent.com/assets/750074/7240442/42a942c0-e7b1-11e4-9a21-7e7a51d1e295.png)

**Comment by lmenezes** [comment]
@kamburi any updates on this?

**Comment by lmenezes** [comment]
@kamburi i will close this issue for now, feel free to open another one if you still have problems
