### ISSUE TITLE
Feature Request: reverse columns and rows in cluster view

### ISSUE THREAD

**Issue by mheese** [lmenezes/elasticsearch-kopf#230]
My elasticsearch clusters normally have a lot of more indices than cluster nodes. It would be extremely helpful if the cluster nodes would be columns instead of rows, and the indices would be rows instead of columns. Maybe making it switchable is even the best, because I can imagine that the current view can be better in some cases.

**Comment by lmenezes** [comment]
@mheese hey, there are 2 issues here:

1- Rendering a long list of indices x shards can make the view quite slow. Having them paginated somehow makes this a little "snappier".

2- Usually, people have a lot more indices than nodes. Still, it's normal that people have more than say, 7 nodes(which is the number of index columns I can currently fit on my display size). If rows x columns were reversed, that means that for a given index, I might not see where its shards are all at once(I have 10 data nodes).

On the other hand... what's your use case for looking at all indices at once? Are you actually interested on the shard allocation, or just having a list with all of them? I have on my pipeline to have a indices view(such as the nodes view which is already done), but would be more of index x index stats(number of documents, size...).
