### ISSUE TITLE
removed features?

### ISSUE THREAD

**Issue by natefox** [lmenezes/elasticsearch-kopf#234]
I just upgraded from 1.3.6 to 1.4.5 and noticed 2 of the features I use quite a bit are gone: ability to filter for just the 'unhealthy' indices as well as the 'stethoscope page' with the health information.

Will either of those features be coming back in one form or another?

I know 1.4.5 shows the # of shards initializing and unassigned, but its nice to see which ones. Maybe the ability to click on those two lines (when they exist) will enable a filtering mode of some kind?

I definitely like the new nodes tab!

**Comment by lmenezes** [comment]
@natefox hey,
yes, I tried cleaning up a bit the shards view and had to compromise

For the unhealthy filter, I actually thought(even though this is currently not implemented), just always sorting by unhealthy -> healthy, and then, asc/desc by name. This way, I don't need another component to control that, and in case there are unhealthy indices, they will be display first in the list anyway. What do you think about this?

As for the stethoscope page, what did you use that for? I initially thought this could be useful to actually share your cluster information through a github gist. But honestly, I might have used that once or twice. If you actually used that, I would like to know what for, so I can either reconsider fitting that somewhere else(I used that space for sorting indices), or might offer the same use case in a different way.

**Comment by natefox** [comment]
I love the idea of always putting unhealthies first. Saves UI space and makes it very usable.

As for health page, my less advanced guys would use it for getting the hot threads to figure out why a certain box was running hot. I admit it was rarely used as well. 
Its not hard to run it from the API though, so if that page is removed entirely, I wont cry :)

**Comment by rgardam** [comment]
I second this. Non healthy index's is really really useful. 
Showing only the non healthy ones would be really cool still to be able to do.

**Comment by bflad** [comment]
:+1: for unhealthy indices being extremely helpful

**Comment by lmenezes** [comment]
![screenshot 2015-03-09 22 51 52](https://cloud.githubusercontent.com/assets/750074/6565300/4c0d6a80-c6af-11e4-8c62-2a0bde2e05d8.png)
![screenshot 2015-03-09 22 52 03](https://cloud.githubusercontent.com/assets/750074/6565301/4c0ea3c8-c6af-11e4-94bc-f548a0c1b990.png)

the option is only exposed when there are unhealthy indices. In the case that the filter is enabled(to show only unhealthy) and the cluster becomes green, the filter then is just dropped, since otherwise there would be no way of changing it.

hope it works ok :)

**Comment by rgardam** [comment]
Works great for me!

**Comment by lmenezes** [comment]
@rgardam happy to hear :+1:
