### ISSUE TITLE
cluster page does not show master only nodes

### ISSUE THREAD

**Issue by mantunovic** [lmenezes/elasticsearch-kopf#235]
I have 14 nodes cluster: 3 masters (2 master only and 1 master+data node) and 12 data only, I upgraded to 1.4.6 and now on page http://localhost:9200/_plugin/kopf/#!/cluster I see only data nodes.

Masters are shown only on nodes page http://localhost:9200/_plugin/kopf/#!/nodes

I am using elasticsearch 1.4.3

**Comment by lmenezes** [comment]
@mantunovic this is intentional. The idea is that this page will become really, a shard map(so, only nodes with shards should be there). For viewing other node types, you should now use the nodes page.
