### ISSUE TITLE
Storing multiple connections/handling with mappings

### ISSUE THREAD

**Issue by hellboy81** [lmenezes/elasticsearch-kopf#236]
Can `elasticsearch-kopf` store multiple named connections to easily connect with server/store?
Can `elasticsearch-kopf`manage mappings explicitly (register(create)/change/delete)?

**Comment by lmenezes** [comment]
@hellboy81 hey

not really sure if I understood your questions correctly, but:

1- currently no list of servers is pre populated, but it does keep a list of previous hosts you connected to(if you do that through that link): 
![screenshot 2015-04-07 18 27 52](https://cloud.githubusercontent.com/assets/750074/7028091/f14a2d70-dd53-11e4-87d3-b0df1132cea1.png). 

2- Not really sure what you mean here. Could you elaborate a little? :)

**Comment by up-town-down** [comment]
I think what hellboy81 is getting at is the ability to manipulate index mappings from within the kopf ui in the same way as you can manipulate index/cluster settings - at the moment I think you can only do this by dropping the correctly formatted JSON into the REST tab. I think it could be a useful feature, but given how complex a mapping can get with different fields, analysis and embedded fields/array options it might be difficult to do something all inclusive.

**Comment by lmenezes** [comment]
@up-town-down thanks for the insight :)

@hellboy81 and as mentioned on the previous comment, there is no such feature currently, and I doubt I will ever get time to implement that properly. Sorry :(
