### ISSUE TITLE
grunt task to stop server

### ISSUE THREAD

**Issue by hellboy81** [lmenezes/elasticsearch-kopf#237]
Is there grunt task to stop server?

How can I stop server?

**Comment by lmenezes** [comment]
@hellboy81 not that I know of, but then again, I know very little about grunt. I personally don't use grunt to run kopf. maybe @rcsole knows more :)

**Comment by rcsole** [comment]
@hellboy81 what do you mean to stop the server? I don't understand the question.

If anything you'd use grunt to run a local server to develop kopf. Can you explain a little
bit further what is it you need?
