### ISSUE TITLE
Can not open/close indices anymore

### ISSUE THREAD

**Issue by juliendangers** [lmenezes/elasticsearch-kopf#239]
Hello,
I was using 1.4.3 version before, but installed 1.4.6 today, and I can not open or close index anymore. It was a really useful feature for us, any chance of having it back ? (it was really faster than a curl command :p)

Edit: Actually, sometimes the option is available, sometimes isn't :/

**Comment by lmenezes** [comment]
hum... I can't reproduce this(and this is not intentional). If this happens again(even better if you can somehow reproduce), could you copy the output given by the REST APIs? A screen shot would also help me understand what exactly is missing.

**Comment by juliendangers** [comment]
Here is one screenshot with the open/close feature, and another without

![close-available](https://cloud.githubusercontent.com/assets/1092527/6414760/4d5608e2-be9a-11e4-918c-49cd4f8edd53.png)
![index_closed](https://cloud.githubusercontent.com/assets/1092527/6414759/4d557760-be9a-11e4-862e-7bd24c7c990a.png)

**Comment by juliendangers** [comment]
I think it might comes from the fact that 3 of our 13 nodes, still have 1.4.3 version :(
Is the feature still available in 1.4.6 ?

**Comment by lmenezes** [comment]
hum, on the second picture I can read shards: 0 * 1... which is a bit odd. Maybe your cluster has problems atm?

**Comment by juliendangers** [comment]
it's because the index is closed

**Comment by lmenezes** [comment]
hum, odd then, because the color of the text indicates otherwise. When an index is closed, the text should by this dark gray:
![screenshot 2015-02-27 16 22 50](https://cloud.githubusercontent.com/assets/750074/6415139/412264be-be9d-11e4-8b89-40e6a8fcd9c3.png)

Could you send me the output of /_cluster/state ?

**Comment by juliendangers** [comment]
yes, this is one of the others things I noticed with the new version, before closed indices had the dark gray colors. I would love to give you the output, unfortunately it contains informations about our clients (names at least).
Once I'll shutdown the 3 old nodes, I will try again, and I'll come back to you ;)

**Comment by lmenezes** [comment]
I'm only interested in a couple of things:
```
blocks: {
  indices: {
    INDEX_NAME: { }
```
so here the content of index_name

and then:
```
metadata: {
  indices: {
    INDEX_NAME: {
      state: THIS_VALUE
```

**Comment by lmenezes** [comment]
(of course, both referring to the index of the screenshot)

**Comment by juliendangers** [comment]
filter for open/closed indices is working, I have only 67 open indices over 212 indices, and the API gives the right state. I really think the problem is due to the difference of version, since this is the only change we got on our cluster ;) (I should have wait before opening an issue, my bad)

**Comment by lmenezes** [comment]
sure, let me know how it goes. but, having different versions of kopf on different nodes should not be a problem :)

**Comment by juliendangers** [comment]
I stopped old nodes, and problem is solved ;)
I have open/close feature, and closed indices have dark grey color \o/

Sorry for the false positive :(
