### ISSUE TITLE
Handling unstable clusters

### ISSUE THREAD

**Issue by up-town-down** [lmenezes/elasticsearch-kopf#240]
Hi!

Firstly, just wanted to say thanks for a great tool, it's really helped me in getting stuck into elasticsearch as there are so many features and options having the basics in something easy to use made a big difference!

Onto my query:

Something that really causes issues for me is when the cluster is in a 'bad state', to be fair this mostly occurs for me during early development when I am restarting nodes and adjusting settings constantly to tweak bits and pieces.

Take this example; I set-up a small cluster and set the minimum master nodes to 2 as that's what I need to avoid split brain across two pools (I'm using shard allocation awareness). Now if I shutdown or restart one of the master nodes the cluster goes into 503. As far as I can tell this breaks kopf, as to return any info seems to rely on a 200 OK response upon initial connection. This makes it difficult to use kopf to diagnose an issue in the case where the problem has happened independently e.g. power failure to a pool or a failure of a significant enough proportion of the master nodes. However, if you have at least one operational master and you point your browser at it you can still read the _nodes path, it would be nice if kopf could still pull this on a 503 error as it would be really useful in fault resolution (rather than having to read reams of json output to figure out which node needs kicking). You can also read the cluster status detail, albeit by forcing local e.g. _cluster?local.

I was thinking it could do some logic:
1. if a 503 is reported, set the ui to red (rather than grey as now)
2. try pulling the _cluster?local from the master you are connected to
3. if that works (indicating at least the master you are connected to is in good order) pull the nodes data.

Although 2 doesn't offer much I'd definitely like to see 3.

I should say I *am* a software developer but I've spent so much time as a manager that I only have a little JavaScript knowledge and the Angular (despite looking) I can't make heads nor tails of, otherwise I'd offer to prototype it myself :-)

Appreciate any thoughts (other than stop being a manger and go learn code :P)

**Comment by lmenezes** [comment]
@up-town-down sounds reasonable, but I will have to check what I can actually get from a cluster reporting 503. Will let you know as soon as I have some time to look into it :)

**Comment by up-town-down** [comment]
@lmenezes - thanks, I've experimented with the logic a fair bit and I think it looks sound, though I appreciate you'll want to test it properly in case it has any undesired effects!

For completeness sake:

1. Currently when connecting and the master node you are trying to connect to is dead error returned by kopf is "Error connecting to [node url]"
2. if node is up and cluster is 200 ok, but shards are unassigned (_cluster/state readable) banner is yellow/amber
3. 200 ok and all shards assigned (green banner)
4. currently if cluster goes 503 (tested by setting minimum master nodes to 2 and starting 1 node) kopf reports "Error refreshing cluster state", banner is grey and clicking on the detail shows 503. _cluster/state will not respond, _nodes/stats/nodes repsonds. _cluster/state?local responds

So if a 503 is thrown it's still possible to get nodes and (local) cluster state. The only problem I foresee is if the cluster is split because 2 pools (assume different data centres/sites) are disconnected as kopf will be reporting local cluster status not the whole cluster, but I think the benefits i.e. some node status vs. nil will most likely outweigh the cost.

I'm worried it might be a lot of logic changing and I'm sorry I'm too stupid to help, but would love it if you could :)

**Comment by up-town-down** [comment]
This is awesome, thanks for doing it, it's making my life so much easier!

**Comment by lmenezes** [comment]
no problems :)
Currently is still very very basic what it does, but I suppose this can be improved little by little.

**Comment by up-town-down** [comment]
Sorry @lmenezes but I think this might have busted in the latest release, I'm seeing the "no master node" message and the tab switch to the nodes tab, but there is no data :(

**Comment by lmenezes** [comment]
@up-town-down sorry about that :) should be fixed in 1.4.9 which i just pushed. This handling a broken cluster workflow is still quite brittle, but will try to find sometime to add some tests to it. thanks for letting me know.

**Comment by up-town-down** [comment]
Heh, I know what you mean, any code I write is pretty brittle! I'll give 1.4.9 a go and post back if there are any issues. Cheers!
