### ISSUE TITLE
Remember refresh rate / theme

### ISSUE THREAD

**Issue by dklotz** [lmenezes/elasticsearch-kopf#243]
In kopf 1.4.6 / ES 1.4.4 every time I close the browser window/tab, kopf seems to forget the refresh rate / theme I have set there. I seem to remember that this was saved (cookie? local storage?) in older versions. Regardless if my memory is correct or not, this would be really nice to have (especially since the default refresh rate of 5s can be too much for my slow connection to our production cluster sometimes).

Or is this feature there and there's a problem in my configuration / installation? Default install using bin/plugin install..., albeit in a docker container and behind an nginx reverse proxy.

**Comment by lmenezes** [comment]
hey,
I removed this feature in favor of having that configurable on a property file(not documented yet, sorry :)). Having both options could give space for some uncertainty regarding which option is taken into account and what has priority over what.
The file is https://github.com/lmenezes/elasticsearch-kopf/blob/master/kopf_external_settings.json
That works for you?

**Comment by dklotz** [comment]
Hmm, as a workaround (i.e. for the refresh time) that's OK, but e.g. the light/dark theme is really a personal preference, and since our cluster has several users, setting that globally isn't really a great idea. And I don't really see the problem in having default values in that settings file and being able to override them on a user-by-user basis. But of course it's just a small nuisance, not a real problem. :)

**Comment by jthi3rry** [comment]
Hey @lmenezes, I would tend to agree with @dklotz. The ability to choose a theme would be better left on the client side as this is a user specific choice. Although being able to set defaults via a config file is a good feature, keeping easy access to the theme and refresh rate (and remembering these choices) would be great so everybody doesn't have to agree with the devop installing the plugin :-)
