### ISSUE TITLE
kopf uses wrong cluster

### ISSUE THREAD

**Issue by glenavery** [lmenezes/elasticsearch-kopf#245]
I have kopf installed on fedora with elasticsearch 1.4.4. It was working fine, however after changing the cluster name and then restarting elasticsearch, kopf kept trying to use the old cluster name so was not displaying any information (i.e. the old cluster name was still displayed on the top right before the hostname). A GET on :9200 for elasticsearch was displaying the correct cluster name however as well as being correct in kibana and marvel.

It seems that kopf is storing some config data somewhere which did not get updated?

**Comment by lmenezes** [comment]
silly question, but did you try refreshing kopf(just a normal page refresh on the browser)?

**Comment by glenavery** [comment]
Yup, also tried restarting the browser, removing and readding the kopf plugin and while restarting elasticsearch between each step.

**Comment by lmenezes** [comment]
which version of kopf are you using?

**Comment by glenavery** [comment]
1.4.3

On 4 March 2015 at 15:01, leonardo menezes <notifications@github.com> wrote:

> which version of kopf are you using?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lmenezes/elasticsearch-kopf/issues/245#issuecomment-77162043>
> .
>



-- 

mvh
Glen
070 8715166

**Comment by lmenezes** [comment]
are there any javascript errors on the console? 
If not, could you copy the output of the rest requests? And also a screen shot of the cluster overview?

**Comment by glenavery** [comment]
Hi! It starting working now, I removed and readded kopf from the zip file and now it has updated.

Thanks for the quick replies!
