### ISSUE TITLE
Try it online link fails 

### ISSUE THREAD

**Issue by vitaly-krugl** [lmenezes/elasticsearch-kopf#246]
The top README.md has a "Try it online" URL. When I click on the "Try it online" link http://lmenezes.com/elasticsearch-kopf/?location=http://localhost:9200, the resulting page displays the error message `Error connecting to [http://lmenezes.com:80]`

**Comment by lmenezes** [comment]
Which version of elasticsearch are you running? If you are running a rather new version, CORS is disabled and the link won't work. Probably the same issue as: https://github.com/lmenezes/elasticsearch-kopf/issues/195

**Comment by vitaly-krugl** [comment]
@lmenezes, thank you for your quick response. I thought that the URL on your repo's front page http://lmenezes.com/elasticsearch-kopf/?location=http://localhost:9200 was a demo on your server. I didn't realize that I needed to have my own elasticsearch running in order to use the demo.

I also couldn't find documentation for Kopf (except what's on the repo's front page).  I wanted to check it out to see how it compares with Head and what differences there are between Head and Kopf plugins.

**Comment by lmenezes** [comment]
@vitaly-krugl ah, got you. Unfortunately there isn't a demo server, so you would just have to install both on a local instance to compare :)
