### ISSUE TITLE
Client nodes showing 0 disk usage

### ISSUE THREAD

**Issue by eugenp** [lmenezes/elasticsearch-kopf#248]
I am using version 1.4.6 of the plugin and I'm seeing correct readings in the `Nodes` tab, the `disk usage` column for all nodes except Client Slaves (there are 2 client slaves in the cluster). Here's what it looks like (attached image): 
![kopf_disk_space](https://cloud.githubusercontent.com/assets/1022859/6658074/97ede96e-cb66-11e4-9f71-e1b25885f3d7.jpg)
I'm assuming this is a bug, but then again I might be missing something. Thanks, 
Eugen.

**Comment by lmenezes** [comment]
Hey @eugenp 
yeah, this is somehow a bug. The disk usage doesn't report the node disk, but the data partition used for elasticsearch. Being a client node, there is no data partition associated with the node.
Should anyway display that differently so it's clear.

thanks for reporting :)

**Comment by eugenp** [comment]
That makes sense. Yeah - a clearer message would probably be good - but it's not a major thing of course. Thanks, 
Eugen.
