### ISSUE TITLE
"Error connecting" to a remote ES

### ISSUE THREAD

**Issue by vorou** [lmenezes/elasticsearch-kopf#249]
I'm on `bab58fe361294f5d7068d3c86ed8241d5`. It works find when connecting to localhost. But connecting by ip to a remote ES returns "Error connecting".

But there *is* a ES instance on that address:
```
> http 192.168.66.36:9200
HTTP/1.1 200 OK
Content-Length: 326
Content-Type: application/json; charset=UTF-8

{
    "cluster_name": "gofra",
    "name": "gofra1",
    "status": 200,
    "tagline": "You Know, for Search",
    "version": {
        "build_hash": "927caff6f05403e936c20bf4529f144f0c89fd8c",
        "build_snapshot": false,
        "build_timestamp": "2014-12-16T14:11:12Z",
        "lucene_version": "4.10.2",
        "number": "1.4.2"
    }
}
```

What am I doing wrong? Is it supposed to work with a remote host? Could it be related to ES version (localhost is `1.2.1`)?

**Comment by lmenezes** [comment]
could it be related with https://github.com/lmenezes/elasticsearch-kopf/issues/195 ?

**Comment by vorou** [comment]
That was it. Adding `http.cors.enabled: true` did the trick.
Thanks! Should have looked harder before asking.

**Comment by lmenezes** [comment]
@vorou no problems, I should also have documented that.. ;)
