### ISSUE TITLE
Labels missing from heap, cpu and disk graphs for nodes on the Cluster tab.

### ISSUE THREAD

**Issue by dbeckham** [lmenezes/elasticsearch-kopf#250]
Tested in latest Firefox and Chrome for both Light and Dark themes.  The labels for the small bar graphs for node resources are missing. You can't tell what these things are with out hovering over for the graph and wait for the browser to show the title attribute as a tooltip.

**Comment by lmenezes** [comment]
@dbeckham that was intentionally removed(actually, the bars were also removed but then brought back).
I'm hoping to move all of the "monitoring" features from the cluster view(or at least leave the bare minimum) to the nodes view.

**Comment by lmenezes** [comment]
@dbeckham do you really miss the labels? 
also, thanks for reporting :)

**Comment by dbeckham** [comment]
@lmenezes I wouldn't say miss them as much as they don't mean anything without labels to someone who hasn't memorized what they are.  I don't necessarily look at kopf every day and when I do, I may be doing something other than looking at those bar graphs.  With the labels missing, I have to hover over them to remember what they are. It probably seems pointless to you since you intimately know kopf and every nook and cranny, but it's not good UI to make the user guess what they are looking at. For someone who just downloaded Kopf, instead of intuiting and instantly taking in the UI to see the state of their cluster, they go "huh, what are those blue bars for?"  That's not what a dashboard is supposed to make a user do.  Those graphs are definitely much less useful now that the nodes tab has so much detail, but if you plan to leave them, label them for your users. =)

Kopf is awesome, by the way. It really is the best tool out there right now and I'll often use it first before I go poking through Marvel.
