### ISSUE TITLE
Make gist url configurable

### ISSUE THREAD

**Issue by jgarland79** [lmenezes/elasticsearch-kopf#252]
We have a github enterprise server with our own internal gist. I would like to be able to point this to our own server.

https://github.com/lmenezes/elasticsearch-kopf/blob/e30c821f6767a6b389e80616fd711b2dd048ab42/dist/kopf.js#L523

**Comment by lmenezes** [comment]
@jgarland79 hey.. that might be more complicated than it seems. sometime ago I actually removed this feature. Even though the code is still there, there is no direct link from the interface anymore.

As all features, I really dont have numbers on how many people use them or not, and usually I just decide what stays and what goes based on gut feeling. I could leave everything, but I'd then end up with this super cluttered interface.

So far you are the 2nd person that talks about this feature, and the other, didn't really use it. So I assume is not really critical. Would you mind sharing what you use this for? Maybe I could build some kind of replacement or, place an access point somewhere else that still works for you.
