### ISSUE TITLE
Make favicon reflect the status color

### ISSUE THREAD

**Issue by amosshapira** [lmenezes/elasticsearch-kopf#255]
I have Kopf open in a Chrome tab all the time but its favicon is useless.

It would be very useful if the favicon reflected the cluster's status - a simple background colour same as the status (red, yellow, green) would be very useful.

**Comment by lmenezes** [comment]
makes sense. will try to come up with some meaningful icon for kopf, and then handle the color changes :+1:

**Comment by amos-stan** [comment]
Thanks. It looks great.

**Comment by lmenezes** [comment]
@amos-stan thank you actually. really nice idea, my colleagues also really liked it :+1:

**Comment by koocotte** [comment]
It does not work here; and I don't know why. Firefox 35.0.1 & kopf 1.4.8. kopf is behind a reverse-proxy in a subdirectory but all requests are answered by HTTP/200. /elasticsearch-kopf/favicon.ico is loaded successfully (a black disc).

Kopf is working, the top bar is green/yellow according to my cluster status, but the favicon is completely transparent.

**Comment by lmenezes** [comment]
@koocotte did you try with a different browser? I don't really test on anything other than chrome :)

**Comment by koocotte** [comment]
No, sorry, I can't install chrome here. Anyway it's a minor problem. Thanks.

**Comment by amos-stan** [comment]
I've just installed Firefox on my Mac to test this and it doesn't show the Favicon for me either.
I use the public hosted Kopf at http://lmenezes.com/elasticsearch-kopf/.
Google'ing about Firefox and Favicon comes up with many pages about issues regarding this (i.e. Firefox not displaying favicon which is displayed fine by other browsers).
