### ISSUE TITLE
"Error refreshing cluster state" when an index is in read-only mod

### ISSUE THREAD

**Issue by pauledouard** [lmenezes/elasticsearch-kopf#258]
Hello,

I'm trying to set an index a read only during a reindexing script, and it causes kopf to crash during the operation. As soon as the index is set back to read&write mode, kopf 'revives'.
I've checked my cluster with another monitoring plugin (head), and it worked properly.

The python command I use that set the index in read only mod is the following:
es.indices.put_settings({"index" : {"blocks": {"read_only": True} } }, index=index)

Thanks.

EDIT: I'm using version 1.4.7 of kopf

**Comment by lmenezes** [comment]
hey, which version of elasticsearch are you using?
I'm testing with v1.4.1 of elasticsearch + kopf 1.4.7 and cannot reproduce this issue.

I tried 
```
curl -XPUT http://localhost:9200/foo/bar/1 -d '{"id": 1}'
curl -XPUT http://localhost:9200/foo/_settings -d '{"index.blocks.read":"true","index.blocks.write":"true"}'
```

and to be sure all is good: 
```
curl -XGET http://localhost:9200/foo/_settings
```
and got
```json
{  
  "foo":{  
    "settings":{  
      "index":{  
        "creation_date":"1429185925912",
        "number_of_shards":"5",
        "uuid":"thN8P-8ZRMG4HjZvcdI5bQ",
        "version":{  
          "created":"1040199"
        },
        "number_of_replicas":"1",
        "blocks":{  
          "write":"true",
          "read":"true"
        }
      }
    }
  }
}
```

![screenshot 2015-04-16 14 09 58](https://cloud.githubusercontent.com/assets/750074/7180462/5453a528-e442-11e4-975b-68a88347feaf.png)

**Comment by pauledouard** [comment]
Thanks for the fast answer.

We're using elasticsearch 1.5.0. 

You are right, setting "index.blocks.write" to True does not create any issue. However, setting "index.blocks.read_only" seems to be the issue.

**Comment by lmenezes** [comment]
yep, now I see what this is about. There is an old ticket https://github.com/elastic/elasticsearch/issues/2833 talking about this issue. It's actually an elasticsearch bug... And this affects actually both _status and _aliases calls.

I checked this issue with head, and it actually doesnt seem to work as well(if you open it after applying this settings to the index). If its already open, it wont report a problem, but also wont update the information there(try creating an index, for example).

So, not really much I can do :(

**Comment by pauledouard** [comment]
Thanks.

We're going to use "blocks.write" instead of "blocks.read_only", it works just fine.
