### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by spuder** [lmenezes/elasticsearch-kopf#259]
I use kopf all the time. It would be nice if it showed a favicon in the browser so it was easier to find. 

![screenshot 2015-04-17 11 04 59](https://cloud.githubusercontent.com/assets/242382/7206755/c8079376-e4f1-11e4-8da1-7e6c925099f8.png)

**Comment by up-town-down** [comment]
@spuder  - Have you seen #255 ? it's just been added in v1.4.8

**Comment by spuder** [comment]
Ah! missed that. Thanks

**Comment by lmenezes** [comment]
@spuder I'm at this moment working on changing the favicon I added on 1.4.8 for something that is also easier to associate with kopf. Should be pushing that really soon :)

**Comment by up-town-down** [comment]
@lmenezes - perhaps a big lower case k in the blob? :P

Seriously tough, it's tough, not a lot of pixels :(

**Comment by lmenezes** [comment]
@up-town-down I already have it done, and it's exactly a k :) But I'm waiting to push that together with a few other visual changes and other enhancements as v1.5.

**Comment by lmenezes** [comment]
![screen shot 2015-04-17 at 22 38 04](https://cloud.githubusercontent.com/assets/750074/7210500/89e8e5ac-e552-11e4-8a9e-8a36a795a2ef.png)

still polishing though :)

**Comment by up-town-down** [comment]
:smile:
