### ISSUE TITLE
Lost the ability to filter by index status

### ISSUE THREAD

**Issue by evantahler** [lmenezes/elasticsearch-kopf#260]
In the lastest version the UI got better, but we lost the ability to filter by index status (closed/opened/unhealthy/etc).

Bring it back please! 

Old ( Good! )

![screen shot 2015-04-21 at 3 26 11 pm](https://cloud.githubusercontent.com/assets/303226/7254422/e8cc821e-e83a-11e4-8e92-1cc026373209.png)

New ( Bad :( )

![screen shot 2015-04-21 at 3 26 45 pm](https://cloud.githubusercontent.com/assets/303226/7254432/f0b07986-e83a-11e4-9058-11b481bc8ce9.png)

**Comment by lmenezes** [comment]
@evantahler hey, if you mean the unhealthy part, it's actually still there(but only visible when it actually makes sense):
![screenshot 2015-04-21 16 29 48](https://cloud.githubusercontent.com/assets/750074/7254495/c6931506-e843-11e4-8527-5bff58d8f876.png)
![screenshot 2015-04-21 16 29 57](https://cloud.githubusercontent.com/assets/750074/7254494/c68f7856-e843-11e4-8d7f-235034d7b74a.png)

Or do you mean filtering for only closed indices(which I assume might not be really usual)?

**Comment by evantahler** [comment]
One of the use cases I've used Kopf for was rolling upgrades of the cluster.  We've got a lot of indexes, so it's helpful to watch which indexes are still rebalancing (unhealthy) before the cluster goes green again.  Filtering to see only "unhealthy" indexes was helpful to predict how much longer the cluster would be yellow, etc.

**Comment by evantahler** [comment]
Oh... the pictures just loaded.  The "show only unhealthy indexes" button was what I was looking for!  

Keep up the great work!

**Comment by lmenezes** [comment]
@evantahler thanks :)
