### ISSUE TITLE
Disk usage does not show full info.

### ISSUE THREAD

**Issue by phungle** [lmenezes/elasticsearch-kopf#261]
I'm using KOPF version 1.5.0.
2 UI issues.
1. Disk usage does not show full info. I can not show how many disk space is free, total.
2. Sometime it can not show "Total data in cluster".

**Comment by lmenezes** [comment]
@phungle could you send a screen shot explaining what you mean? 

and which version of elasticsearch are you running?

**Comment by phungle** [comment]
Hi Leonardo,

I�m upgrading disk space for our cluster.
We have 3 instances. 
To upgrade, I create new instance, add to cluster and turn off one of them.
New instance will have new kopf v1.5.0. Old instance has old version.
I think they have conflicted.
Now all of them have kopf v1.5.0 & it works perfectly.

Thanks,
Phung Le

**Comment by lmenezes** [comment]
@phungle Good to hear. Did you also change elasticsearch versions? There should be no conflict between kopf version, its just javascript running on your browser :)
