### ISSUE TITLE
Close Kopf by htaccess

### ISSUE THREAD

**Issue by popovae** [lmenezes/elasticsearch-kopf#262]
Hello!

Does anybody know if there is any way to close access to Kopf (via htaccess or any other way except firewalls and so on)?

**Comment by lmenezes** [comment]
@popovae you likely want to cut undesired access to elasticsearch instead of kopf :)

**Comment by popovae** [comment]
@lmenezes Totally different things:))

**Comment by lmenezes** [comment]
@popovae why would block kopf but not elasticsearch APIs?

**Comment by popovae** [comment]
@lmenezes well...ES is under Firewall now, access is allowed from any IP inside network. But we need to close access to Kopf (as we did with Kibana for example...)

**Comment by lmenezes** [comment]
@popovae that's what I meant before, if access to elasticsearch is allowed from inside the network, closing access to kopf doesn't actually give you much. 
But I guess one option could be having kopf running on a different server other than elasticsearch, and securing this server in any way you want. You would have to enable CORS on elasticsearch though.

**Comment by up-town-down** [comment]
@popovae - Something like this -http://httpd.apache.org/docs/2.2/howto/auth.html#satisfy - should do the trick, if you install it on a separate server as @lmenezes  suggested either using a folder (Easier IMHO) or a virtual host. Personally I did this using J2EE/Jboss and packaging the kopf install as a .war which works quite nicely, as we have a nice out of hte box framework in the office - I still haven't got round to the other part, actually protecting elasticsearch itself :P
