### ISSUE TITLE
Relocating shards not visible in 1.4.9

### ISSUE THREAD

**Issue by SecEng** [lmenezes/elasticsearch-kopf#264]
I upgraded from 1.4.4 to 1.4.9 and relocating shards are now longer shown. Unassigned shows and initializing shards are showing up, but relocating shards not not shown anymore.

I'm not sure what information you need in order to debug this. Let me know and I should be able to get you some data.

**Comment by lmenezes** [comment]
@SecEng not really sure what you mean, but I just installed v1.4.9 and did a simple test
![relocating](https://cloud.githubusercontent.com/assets/750074/7301275/f0141d72-e9e1-11e4-8d84-fb1c3e392e20.gif)
:

seems to work ok(initializing shards are displayed in yellow and the relocated shards are displayed in black). 

is that what you meant?

**Comment by SecEng** [comment]
Sorry for not being specific, the count isn't being displayed like it used to.

So when unassigned and initializing shards are happening (in 1.4.9) right above the nodes (below the 4 symbols) it says, 
"x shards unassigned" and "x shards initializing".

In 1.4.4 where it had the shards count(at the top of the page), in small letters it would say "x relocating". (that is also the same spot that had the X for unassigned and initializing).

Does that help?

**Comment by lmenezes** [comment]
@SecEng adding the number of relocating shards on the same place as initializing/unassigned works for you?

**Comment by SecEng** [comment]
That works perfectly for me.
