### ISSUE TITLE
Managing index templates from Kopf

### ISSUE THREAD

**Issue by davmrtl** [lmenezes/elasticsearch-kopf#265]
Should be nice to have a template manager in Kopf.

**Comment by lmenezes** [comment]
@davmrtl what would you expect from a template manager? just some kind of listings of existing templates and options to add/remove them? Similar to what is there for warmers?

**Comment by davmrtl** [comment]
Exactly! This would help me a lot if that screen was added!

**Comment by lmenezes** [comment]
@davmrtl thats doable :) Will get to it whenever I have time

**Comment by davmrtl** [comment]
Ok thanks! ;) Just to be sure, I was talking about the Index Templates: http://www.elastic.co/guide/en/elasticsearch/reference/current/indices-templates.html

**Comment by MonnyA** [comment]
I would find this feature very useful too.

**Comment by lmenezes** [comment]
@davmrtl will be releasing a new version tomorrow with this feature, but its already available if you use it online.

**Comment by davmrtl** [comment]
@lmenezes Thank you so much! I'll take a look at this :)

**Comment by MonnyA** [comment]
This is wonderful, thanks! I have a suggestion for it which I'll add to another issue.
