### ISSUE TITLE
Feature Request - toggle shard reallocation

### ISSUE THREAD

**Issue by spuder** [lmenezes/elasticsearch-kopf#268]
When doing a rolling upgrade, it is very beneficial to toggle shard reallocation on and off. It makes startup perform much faster. 

It would be great if kopf could toggle this on and off. 

Disable
    
    $ELK='http://elasticsearchpool.example.com:9200'
    curl -XPUT $ELK/_cluster/settings -d '{ "transient" : { "cluster.routing.allocation.enable" : "none" } }'

Enable

    curl -XPUT $ELK/_cluster/settings -d '{ "transient" : { "cluster.routing.allocation.enable" : "all" } }'

Resources

http://www.elastic.co/guide/en/elasticsearch/guide/master/_rolling_restarts.html

http://www.elastic.co/guide/en/elasticsearch/reference/1.x/setup-upgrade.html

**Comment by lmenezes** [comment]
hey @spuder 
i think this was one of kopf first features ;)
![screenshot 2015-04-29 20 58 27](https://cloud.githubusercontent.com/assets/750074/7398963/b6040f18-eeb2-11e4-84a5-972fb915db5b.png)

**Comment by lmenezes** [comment]
oh, just noticed moused doesnt appear on the pic. but it's the lock(unlocked, allocation is enabled, locked, not)

**Comment by spuder** [comment]
derp, thanks for pointing that out. I will use that in the future.

**Comment by lmenezes** [comment]
@spuder np :)
