### ISSUE TITLE
Weird issue with favicon and document root

### ISSUE THREAD

**Issue by up-town-down** [lmenezes/elasticsearch-kopf#272]
Hi,

*Sorry this is going to be vague.... :-)*

I'm seeing a weird issue with kopf 1.5.1 and am mid way through a cluster upgrade from es 1.5.0 to 1.5.2. Using Chrome, not sure of version, it's in the office and for security it's segregated so I can't get you a screenshot :-( 

It originally manifested when I up graded the first, master only node to 1.5.2, kopf would no longer connect to it, with elasticsearch failing to return the nodes stats. I *think* this was an es issue, maybe still updating the stats indexing or something... but mention it anyway. I've now upgrade 3 more nodes to 1.5.2 but left the other master at 1.5.0 so I can compare results, kopf returned instantly on the 2nd master but still had the issue I'm going to describe below.

What seems to be happening now is the the favicon is failing to update when the status changes, it persistently says "kopf - no connection" even when there is one. I suspect this is an aspect of my deployment coupled maybe with some hard coded root url somewhere?

My deployment is into a jboss war containing the requisite files which is then protected by some internal libraries that do ldap/certificate verification. The eventual aim is for this war to contain a user api that will proxy queries to es after checking privs. The kopf build is on a separate namespace, kopf is installed at https://myappserver:8443/my-tool/monitor/kopf. When I use the chrome developer tools I can see a failed call to the favicon (at https://myappserver:8443/my-tool/monitor/kopf/favicon.ico), and I also see some failures to https://myappserver:8443/my-tool/monitor/kopf/dist/kopf.js (sorry can't remember the line number, I will double check 2m if I can replicate the issue). The log output on the cluster tab just shows the contents of https://myappserver:8443/ , which in this case is just the default JBoss6 landing page, so not helpful. But weirdly the starts *are* apparently being displayed on all the tabs.

Elasticsearch is on http://myesserver:9200/ so no special config just yet, I was thinking of using elasticsearch-jetty, unless someone in the office springs for the shield plug-in.

Any thoughts gratefully appreciated :-)

**Comment by lmenezes** [comment]
I really don't know what might be happening, but it seems that the request to the favicon is going to right place, but for some reason its not there? 
Looking at the code, I can also see that in this situation, there would be an error while updating the favicon image and that would also make the page title fail.

The issue with the title I can fix quite easy, but the favicon, as far as I understood, it is doing the right thing, except the icon isnt there?

**Comment by up-town-down** [comment]
Thanks. Exactly right, that's the apparent issue. I finished the upgrade of the Cluster yesterday and the 2nd master; the stats api issue didn't resurface, so it rules that out as being involved. I also didn't see a recurrence of the kopf.js error. I think what I'll do when I'm back in the office on Monday is see if I can get someone to clone a new copy from github, in case the icon is missing and/or we've got a corrupted copy of something and run a history clean in case I've got some old code cached in my browser. Will let you know, it may just be "one of those things"!

**Comment by up-town-down** [comment]
re-cloning seems to have worked, it's all good now, unfortunately I didn't get it snapped before 1.5.2 :-( something to do tomorrow! :-)

As an aside, is it possible perhaps to get the JVM short/friendly name out with the version? I'm not sure if that's available as a property in all JVMs. e.g. OpenJDK vs. Oracle. The reasoning is if another member of my team sets up a server or if it's on a different OS it's possible for other JVMs to be used (or if someone messes up and installs another JVM on top of OpenJDK and messes up the defaults)
