### ISSUE TITLE
Easy editing of existing index templates [Enhancement]

### ISSUE THREAD

**Issue by MonnyA** [lmenezes/elasticsearch-kopf#273]
On the index templates page add a way to "load" the template details from the right panel into the left panel including the Template Name and Template Body. This would allow for easy editing of existing templates.

(This new page is so great, thank you so much for it!)

**Comment by lmenezes** [comment]
there you have it :)
just published v1.5.2 with this and some other fixes/improvements.

**Comment by MonnyA** [comment]
Tested it out, it's perfect! :)
