### ISSUE TITLE
Feature Request - Make lock icon easier to notice

### ISSUE THREAD

**Issue by spuder** [lmenezes/elasticsearch-kopf#274]
Typically you usually want to leave the lock unlocked. (To allow shard reallocation). 

It would be nice if kopf changed the color of the lock to a different color (red?) , to reduce the likelihood that you accidentally leave it locked, and loose a node in the cluster. Visually it will catch your attention to remind you to unlock it. 

For example: 

unlocked => lock icon is white
locked => lock icon turns red, or white and black

**Comment by up-town-down** [comment]
+1:
