### ISSUE TITLE
Hot Threads page parsing issue

### ISSUE THREAD

**Issue by MonnyA** [lmenezes/elasticsearch-kopf#275]
Hot threads page doesn't work for me. Kopf v1.5.2. Seems it can't read the response from ES any more because ES is returning an error? Not sure if ES or Kopf issue.

```
[2015-05-13 14:57:00] Elasticseach connection:
[2015-05-13 14:57:00] {"host":"http://vm1.thing.com:9200","withCredentials":false}
[2015-05-13 14:57:09] Error parsing REST API data:
[2015-05-13 14:57:09] {}
[2015-05-13 14:57:09] REST API output:
[2015-05-13 14:57:09] "::: [vm1 C][KH18_zhJRP6ugMQGPDKCyQ][vm1.thing.com][inet[vm1a.thing.com/x.x.x.x:9300]]{data=false, master=false}
 
 0.4% (1.8ms out of 500ms) cpu usage by thread 'elasticsearch[vm1 C][http_server_worker][T#1]{New I/O worker #15}'
 10/10 snapshots sharing following 15 elements
 sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
 sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
 sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:79)
 sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:87)
 sun.nio.ch.SelectorImpl.select(SelectorImpl.java:98)
 org.elasticsearch.common.netty.channel.socket.nio.SelectorUtil.select(SelectorUtil.java:68)
 org.elasticsearch.common.netty.channel.socket.nio.AbstractNioSelector.select(AbstractNioSelector.java:415)
 org.elasticsearch.common.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:212)
 org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
 org.elasticsearch.common.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
 org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
 org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
 java.lang.Thread.run(Thread.java:744)
"
```

**Comment by lmenezes** [comment]
hum.. not sure. will try to reproduce it here. this code is still very "new", and honestly, not really tested in other environments other than a local instance running.
will let you know :)

**Comment by lmenezes** [comment]
@MonnyA found the problem. This commit https://github.com/elastic/elasticsearch/commit/4859ce5d79a786b58b1cd2fb131614677efd6b91 introduced a "Hot threads at..." line that didn't exist before. As I developed against 1.5.1, didn't realise this was new.
Apart from that, found some minor issues when parsing the output(it's parsed so it can be more iterative, even though currently the only thing offered is that you can collapse hot threads from a node). This should all be fixed and with tests, so hopefully also more reliable. 
Let me know if this fixes your problem(just released this on 1.5.3 and with another minor improvement).

thanks for reporting! :+1:

**Comment by MonnyA** [comment]
Hmm. It's now showing the error in the log at the bottom but now in the main body. See image http://i.imgur.com/ajhDwRq.png

Kopf v1.5.3, ES 1.4.4

**Comment by lmenezes** [comment]
@MonnyA that is the hotthreads output, not an error :)
from this pic, everything looks right.

**Comment by MonnyA** [comment]
Ha, shows how much I know about that! Thanks.
