### ISSUE TITLE
Index batch operations

### ISSUE THREAD

**Issue by davmrtl** [lmenezes/elasticsearch-kopf#276]
Would be nice to do batch operations over the indices like:
- Select many indices in the cluster view and call commands
- Or call commands over the filtered indices in the cluster view

**Comment by MonnyA** [comment]
Yes, I was just about to suggest something similar. Maybe have just a simple [multiple select box](http://www.htmlcodetutorial.com/forms/_SELECT_MULTIPLE.html) which would allow the use of Shift and Ctrl to select easily. Or maybe a table with tick boxes showing more information.
For me showing where the shards are or anything more complex isn't needed.

**Comment by lmenezes** [comment]
what kind of batch operations are you thinking about?

**Comment by MonnyA** [comment]
Not sure for @davmrtl but I'd like to be able to mass-delete them easily. I use Curator already but it's useful to mass-delete sometimes too.

**Comment by davmrtl** [comment]
@lmenezes I was hopping that we could:
- Mass-delete filtered indexes
- Mass-optimize filtered indexes
- Mass-close/mass-reopen filtered indexes

(In fact, almost the same functions for individual index, but applied to the filtered indexes)
This would be really usefull for anyone! :)
