### ISSUE TITLE
error to parse cluster data

### ISSUE THREAD

**Issue by jbrablec** [lmenezes/elasticsearch-kopf#277]
[2015-05-18 01:57:31] Elasticseach connection:
[2015-05-18 01:57:31] {"host":"http://localhost:9200","withCredentials":false}
[2015-05-18 01:57:32] Error parsing cluster data:
[2015-05-18 01:57:32] {}
[2015-05-18 01:57:32] REST APIs output:
[2015-05-18 01:57:32] [{"data":{"cluster_name":"my-application","master_node":"DjGb4b4DQkWXQfk2yYnJpA","blocks":{},"routing_table":{"indices":{}}},"status":200,"config":{"method":"GET","transformRequest":[null],"transformResponse":[null],"url":"http://localhost:9200/_cluster/state/master_node,routing_table,blocks/","headers":{"Accept":"application/json, text/plain, */*"}},"statusText":"OK"},{"data":{"_shards":{"total":0,"successful":0,"failed":0},"_all":{"primaries":{},"total":{}},"indices":{}},"status":200,"config":{"method":"GET","transformRequest":[null],"transformResponse":[null],"url":"http://localhost:9200/_stats/docs,store","headers":{"Accept":"application/json, text/plain, */*"}},"statusText":"OK"},{"data":{"cluster_name":"my-application","nodes":{"DjGb4b4DQkWXQfk2yYnJpA":{"timestamp":1431907051805,"name":"Quasar","transport_address":"inet[/127.0.0.1:9300]","host":"pc","ip":["inet[/127.0.0.1:9300]","NONE"],"attributes":

**Comment by lmenezes** [comment]
is that the whole output? seems like the body is cut. Could you paste the rest of it?
also, which version of elasticsearch are you running?

**Comment by jbrablec** [comment]
compiled from source elasticsearch due plugins issue which is solved for now
 
bin/elasticsearch
[2015-05-18 10:49:49,231][WARN ][bootstrap                ] jvm uses the client vm, make sure to run `java` with the server vm for best performance by adding `-server` to the command line
[2015-05-18 10:49:49,436][INFO ][node                     ] [The Grip] version[2.0.0-SNAPSHOT], pid[5876], build[${build/2015-05-17T12:51:22Z]
[2015-05-18 10:49:49,436][INFO ][node                     ] [The Grip] initializing ...
[2015-05-18 10:49:49,464][INFO ][plugins                  ] [The Grip] loaded [], sites [bigdesk, head, kibana, kopf]
[2015-05-18 10:49:49,544][INFO ][env                      ] [The Grip] using [1] data paths, mounts [[System (C:)]], net usable_space [3.8gb], net total_space [119.2gb], spins? [unknown], types [NTFS]
[2015-05-18 10:49:54,175][INFO ][node                     ] [The Grip] initialized
[2015-05-18 10:49:54,175][INFO ][node                     ] [The Grip] starting ...
[2015-05-18 10:49:54,624][INFO ][transport                ] [The Grip] bound_address {inet[/0:0:0:0:0:0:0:0:9300]}, publish_address {inet[/135.76.235.167:9300]}
[2015-05-18 10:49:55,374][INFO ][discovery                ] [The Grip] my-application/7QomAxV8S8aFUf7Zj2k6fA
[2015-05-18 10:49:59,176][INFO ][cluster.service          ] [The Grip] new_master [The Grip][7QomAxV8S8aFUf7Zj2k6fA][CZBRN0344][inet[/135.76.235.167:9300]], reason: zen-disco-join (elected_as_master)
[2015-05-18 10:49:59,243][INFO ][gateway                  ] [The Grip] recovered [0] indices into cluster_state
[2015-05-18 10:49:59,506][INFO ][http                     ] [The Grip] bound_address {inet[/0:0:0:0:0:0:0:0:9200]}, publish_address {inet[/135.76.235.167:9200]}
[2015-05-18 10:49:59,506][INFO ][node                     ] [The Grip] started
[2015-05-18 10:50:29,196][WARN ][cluster.routing.allocation.decider] [The Grip] high disk watermark [10% free] exceeded on [7QomAxV8S8aFUf7Zj2k6fA][The Grip] free: 3.8gb[3.2%], shards will be relocated away from this node
[2015-05-18 10:50:29,197][INFO ][cluster.routing.allocation.decider] [The Grip] high disk watermark exceeded on one or more nodes, rerouting shards
[2015-05-18 10:50:59,188][WARN ][cluster.routing.allocation.decider] [The Grip] high disk watermark [10% free] exceeded on [7QomAxV8S8aFUf7Zj2k6fA][The Grip] free: 3.8gb[3.2%], shards will be relocated away from this node
[2015-05-18 10:51:29,188][WARN ][cluster.routing.allocation.decider] [The Grip] high disk watermark [10% free] exceeded on [7QomAxV8S8aFUf7Zj2k6fA][The Grip] free: 3.8gb[3.2%], shards will be relocated away from this node
[2015-05-18 10:51:59,187][WARN ][cluster.routing.allocation.decider] [The Grip] high disk watermark [10% free] exceeded on [7QomAxV8S8aFUf7Zj2k6fA][The Grip] free: 3.8gb[3.2%], shards will be relocated away from this node
[2015-05-18 10:51:59,188][INFO ][cluster.routing.allocation.decider] [The Grip] high disk watermark exceeded on one or more nodes, rerouting shards
---
[2015-05-18 10:50:31] Elasticseach connection:[2015-05-18 10:50:31] {"host":"http://localhost:9200","withCredentials":false}[2015-05-18 10:50:31] Error parsing cluster data:[2015-05-18 10:50:31] {}[2015-05-18 10:50:31] REST APIs output:[2015-05-18 10:50:31] [{"data":{"cluster_name":"my-application","master_node":"7QomAxV8S8aFUf7Zj2k6fA","blocks":{},"routing_table":{"indices":{}}},"status":200,"config":{"method":"GET","transformRequest":[null],"transformResponse":[null],"url":"http://localhost:9200/_cluster/state/master_node,routing_table,blocks/","headers":{"Accept":"application/json, text/plain, */*"}},"statusText":"OK"},{"data":{"_shards":{"total":0,"successful":0,"failed":0},"_all":{"primaries":{},"total":{}},"indices":{}},"status":200,"config":{"method":"GET","transformRequest":[null],"transformResponse":[null],"url":"http://localhost:9200/_stats/docs,store","headers":{"Accept":"application/json, text/plain, */*"}},"statusText":"OK"},{"data":{"cluster_name":"my-applicatio
 n","nodes":{"7QomAxV8S8aFUf7Zj2k6fA":{"timestamp":1431939031175,"name":"The Grip","transport_address":"inet[/135.76.235.167:9300]","host":"CZBRN0344","ip":["inet[/135.76.235.167:9300]","NONE"],"os":{"timestamp":1431939031175,"uptime_in_millis":22996,"cpu":{"sys":2,"user":5,"idle":91,"usage":7,"stolen":0},"mem":{"free_in_bytes":1335386112,"used_in_bytes":2860240896,"free_percent":36,"used_percent":63,"actual_free_in_bytes":1530908672,"actual_used_in_bytes":2664718336},"swap":{"used_in_bytes":3528790016,"free_in_bytes":4860567552}},"jvm":{"timestamp":1431939031176,"uptime_in_millis":43448,"mem":{"heap_used_in_bytes":72258936,"heap_used_percent":6,"heap_committed_in_bytes":259522560,"heap_max_in_bytes":1046937600,"non_heap_used_in_bytes":20235368,"non_heap_committed_in_bytes":20447232,"pools":{"young":{"used_in_bytes":59717112,"max_in_bytes":214827008,"peak_used_in_bytes":71630848,"peak_max_in_bytes":214827008},"survivor":{"used_in_bytes":8672008,"max_in_bytes":26804224,"peak_u
 sed_in_bytes":8912896,"peak_max_in_bytes":26804224},"old":{"used_in_bytes":3869816,"max_in_bytes":805306368,"peak_used_in_bytes":5302160,"peak_max_in_bytes":805306368}}},"threads":{"count":44,"peak_count":45},"gc":{"collectors":{"young":{"collection_count":3,"collection_time_in_millis":39},"old":{"collection_count":1,"collection_time_in_millis":49}}},"buffer_pools":{"direct":{"count":46,"used_in_bytes":6734646,"total_capacity_in_bytes":6734646},"mapped":{"count":0,"used_in_bytes":0,"total_capacity_in_bytes":0}}},"fs":{"timestamp":1431939031176,"total":{"total_in_bytes":128033222656,"free_in_bytes":4127264768,"available_in_bytes":4127264768,"disk_reads":582472,"disk_writes":327590,"disk_io_op":910062,"disk_read_size_in_bytes":3818600960,"disk_write_size_in_bytes":1964976128,"disk_io_size_in_bytes":5783577088,"disk_queue":"0"},"data":[{"path":"C:\\cygwin\\opt\\elasticsearch\\data\\my-application\\nodes\\0","mount":"C:\\","dev":"C:\\","type":"NTFS","total_in_bytes":128033222656
 ,"free_in_bytes":4127264768,"available_in_bytes":4127264768,"disk_reads":582472,"disk_writes":327590,"disk_io_op":910062,"disk_read_size_in_bytes":3818600960,"disk_write_size_in_bytes":1964976128,"disk_io_size_in_bytes":5783577088,"disk_queue":"0"}]}}}},"status":200,"config":{"method":"GET","transformRequest":[null],"transformResponse":[null],"url":"http://localhost:9200/_nodes/stats/jvm,fs,os","headers":{"Accept":"application/json, text/plain, */*"}},"statusText":"OK"},{"data":{"persistent":{},"transient":{}},"status":200,"config":{"method":"GET","transformRequest":[null],"transformResponse":[null],"url":"http://localhost:9200/_cluster/settings","headers":{"Accept":"application/json, text/plain, */*"}},"statusText":"OK"},{"data":{},"status":200,"config":{"method":"GET","transformRequest":[null],"transformResponse":[null],"url":"http://localhost:9200/_aliases","headers":{"Accept":"application/json, text/plain, */*"}},"statusText":"OK"},{"data":{"cluster_name":"my-application
 ","status":"green","timed_out":false,"number_of_nodes":1,"number_of_data_nodes":1,"active_primary_shards":0,"active_shards":0,"relocating_shards":0,"initializing_shards":0,"unassigned_shards":0,"number_of_pending_tasks":0},"status":200,"config":{"method":"GET","transformRequest":[null],"transformResponse":[null],"url":"http://localhost:9200/_cluster/health","headers":{"Accept":"application/json, text/plain, */*"}},"statusText":"OK"},{"data":{"cluster_name":"my-application","nodes":{"7QomAxV8S8aFUf7Zj2k6fA":{"name":"The Grip","transport_address":"inet[/135.76.235.167:9300]","host":"CZBRN0344","ip":"135.76.235.167","version":"2.0.0-SNAPSHOT","build":"${build","http_address":"inet[/135.76.235.167:9200]","os":{"refresh_interval_in_millis":1000,"available_processors":4,"cpu":{"vendor":"Intel","model":"Core(TM) i5-3340M CPU @ 2.70GHz","mhz":2691,"total_cores":4,"total_sockets":4,"cores_per_socket":1,"cache_size_in_bytes":-1},"mem":{"total_in_bytes":4195627008},"swap":{"total_in_by
 tes":8389357568}},"jvm":{"pid":5876,"version":"1.8.0_45","vm_name":"Java HotSpot(TM) Client VM","vm_version":"25.45-b02","vm_vendor":"Oracle Corporation","start_time_in_millis":1431938987770,"mem":{"heap_init_in_bytes":268435456,"heap_max_in_bytes":1046937600,"non_heap_init_in_bytes":163840,"non_heap_max_in_bytes":0,"direct_max_in_bytes":1046937600},"gc_collectors":["ParNew","ConcurrentMarkSweep"],"memory_pools":["Code Cache","Metaspace","Par Eden Space","Par Survivor Space","CMS Old Gen"]}}}},"status":200,"config":{"method":"GET","transformRequest":[null],"transformResponse":[null],"url":"http://localhost:9200/_nodes/_all/os,jvm","headers":{"Accept":"application/json, text/plain, */*"}},"statusText":"OK"}][2015-05-18 10:50:36] Error parsing cluster data:[2015-05-18 10:50:36] {}[2015-05-18 10:50:36] REST APIs output:[2015-05-18 10:50:36] [{"data":{"cluster_name":"my-application","master_node":"7QomAxV8S8aFUf7Zj2k6fA","blocks":{},"routing_table":{"indices":{}}},"status":200,"
 config":{"method":"GET","transformRequest":[null],"transformResponse":[null],"url":"http://localhost:9200/_cluster/state/master_node,routing_table,blocks/","headers":{"Accept":"application/json, text/plain, */*"}},"statusText":"OK"},{"data":{"_shards":{"total":0,"successful":0,"failed":0},"_all":{"primaries":{},"total":{}},"indices":{}},"status":200,"config":{"method":"GET","transformRequest":[null],"transformResponse":[null],"url":"http://localhost:9200/_stats/docs,store","headers":{"Accept":"application/json, text/plain, */*"}},"statusText":"OK"},{"data":{"cluster_name":"my-application","nodes":{"7QomAxV8S8aFUf7Zj2k6fA":{"timestamp":1431939036175,"name":"The Grip","transport_address":"inet[/135.76.235.167:9300]","host":"CZBRN0344","ip":["inet[/135.76.235.167:9300]","NONE"],"os":{"timestamp":1431939036175,"uptime_in_millis":23001,"cpu":{"sys":2,"user":5,"idle":92,"usage":7,"stolen":0},"mem":{"free_in_bytes":1326972928,"used_in_bytes":2868654080,"free_percent":36,"used_perce
 nt":63,"actual_free_in_bytes":1522561024,"actual_used_in_bytes":2673065984},"swap":{"used_in_bytes":3536105472,"free_in_bytes":4853252096}},"jvm":{"timestamp":1431939036177,"uptime_in_millis":48449,"mem":{"heap_used_in_bytes":72258936,"heap_used_percent":6,"heap_committed_in_bytes":259522560,"heap_max_in_bytes":1046937600,"non_heap_used_in_bytes":20237128,"non_heap_committed_in_bytes":20447232,"pools":{"young":{"used_in_bytes":59717112,"max_in_bytes":214827008,"peak_used_in_bytes":71630848,"peak_max_in_bytes":214827008},"survivor":{"used_in_bytes":8672008,"max_in_bytes":26804224,"peak_used_in_bytes":8912896,"peak_max_in_bytes":26804224},"old":{"used_in_bytes":3869816,"max_in_bytes":805306368,"peak_used_in_bytes":5302160,"peak_max_in_bytes":805306368}}},"threads":{"count":44,"peak_count":45},"gc":{"collectors":{"young":{"collection_count":3,"collection_time_in_millis":39},"old":{"collection_count":1,"collection_time_in_millis":49}}},"buffer_pools":{"direct":{"count":46,"used_
 in_bytes":6734646,"total_capacity_in_bytes":6734646},"mapped":{"count":0,"used_in_bytes":0,"total_capacity_in_bytes":0}}},"fs":{"timestamp":1431939036178,"total":{"total_in_bytes":128033222656,"free_in_bytes":4127191040,"available_in_bytes":4127191040,"disk_reads":582474,"disk_writes":327604,"disk_io_op":910078,"disk_read_size_in_bytes":3818637824,"disk_write_size_in_bytes":1965882368,"disk_io_size_in_bytes":5784520192,"disk_queue":"0"},"data":[{"path":"C:\\cygwin\\opt\\elasticsearch\\data\\my-application\\nodes\\0","mount":"C:\\","dev":"C:\\","type":"NTFS","total_in_bytes":128033222656,"free_in_bytes":4127191040,"available_in_bytes":4127191040,"disk_reads":582474,"disk_writes":327604,"disk_io_op":910078,"disk_read_size_in_bytes":3818637824,"disk_write_size_in_bytes":1965882368,"disk_io_size_in_bytes":5784520192,"disk_queue":"0"}]}}}},"status":200,"config":{"method":"GET","transformRequest":[null],"transformResponse":[null],"url":"http://localhost:9200/_nodes/stats/jvm,fs,os
 ","headers":{"Accept":"application/json, text/plain, */*"}},"statusText":"OK"},{"data":{"persistent":{},"transient":{}},"status":200,"config":{"method":"GET","transformRequest":[null],"transformResponse":[null],"url":"http://localhost:9200/_cluster/settings","headers":{"Accept":"application/json, text/plain, */*"}},"statusText":"OK"},{"data":{},"status":200,"config":{"method":"GET","transformRequest":[null],"transformResponse":[null],"url":"http://localhost:9200/_aliases","headers":{"Accept":"application/json, text/plain, */*"}},"statusText":"OK"},{"data":{"cluster_name":"my-application","status":"green","timed_out":false,"number_of_nodes":1,"number_of_data_nodes":1,"active_primary_shards":0,"active_shards":0,"relocating_shards":0,"initializing_shards":0,"unassigned_shards":0,"number_of_pending_tasks":0},"status":200,"config":{"method":"GET","transformRequest":[null],"transformResponse":[null],"url":"http://localhost:9200/_cluster/health","headers":{"Accept":"application/jso
 n, text/plain, */*"}},"statusText":"OK"},{"data":{"cluster_name":"my-application","nodes":{"7QomAxV8S8aFUf7Zj2k6fA":{"name":"The Grip","transport_address":"inet[/135.76.235.167:9300]","host":"CZBRN0344","ip":"135.76.235.167","version":"2.0.0-SNAPSHOT","build":"${build","http_address":"inet[/135.76.235.167:9200]","os":{"refresh_interval_in_millis":1000,"available_processors":4,"cpu":{"vendor":"Intel","model":"Core(TM) i5-3340M CPU @ 2.70GHz","mhz":2691,"total_cores":4,"total_sockets":4,"cores_per_socket":1,"cache_size_in_bytes":-1},"mem":{"total_in_bytes":4195627008},"swap":{"total_in_bytes":8389357568}},"jvm":{"pid":5876,"version":"1.8.0_45","vm_name":"Java HotSpot(TM) Client VM","vm_version":"25.45-b02","vm_vendor":"Oracle Corporation","start_time_in_millis":1431938987770,"mem":{"heap_init_in_bytes":268435456,"heap_max_in_bytes":1046937600,"non_heap_init_in_bytes":163840,"non_heap_max_in_bytes":0,"direct_max_in_bytes":1046937600},"gc_collectors":["ParNew","ConcurrentMarkSwe
 ep"],"memory_pools":["Code Cache","Metaspace","Par Eden Space","Par Survivor Space","CMS Old Gen"]}}}},"status":200,"config":{"method":"GET","transformRequest":[null],"transformResponse":[null],"url":"http://localhost:9200/_nodes/_all/os,jvm","headers":{"Accept":"application/json, text/plain, */*"}},"statusText":"OK"}][2015-05-18 10:50:41] Error parsing cluster data:[2015-05-18 10:50:41] {}[2015-05-18 10:50:41] REST APIs output:[2015-05-18 10:50:41] [{"data":{"cluster_name":"my-application","master_node":"7QomAxV8S8aFUf7Zj2k6fA","blocks":{},"routing_table":{"indices":{}}},"status":200,"config":{"method":"GET","transformRequest":[null],"transformResponse":[null],"url":"http://localhost:9200/_cluster/state/master_node,routing_table,blocks/","headers":{"Accept":"application/json, text/plain, */*"}},"statusText":"OK"},{"data":{"_shards":{"total":0,"successful":0,"failed":0},"_all":{"primaries":{},"total":{}},"indices":{}},"status":200,"config":{"method":"GET","transformRequest":
 [null],"transformResponse":[null],"url":"http://localhost:9200/_stats/docs,store","headers":{"Accept":"application/json, text/plain, */*"}},"statusText":"OK"},{"data":{"cluster_name":"my-application","nodes":{"7QomAxV8S8aFUf7Zj2k6fA":{"timestamp":1431939041177,"name":"The Grip","transport_address":"inet[/135.76.235.167:9300]","host":"CZBRN0344","ip":["inet[/135.76.235.167:9300]","NONE"],"os":{"timestamp":1431939041177,"uptime_in_millis":23006,"cpu":{"sys":1,"user":1,"idle":96,"usage":2,"stolen":0},"mem":{"free_in_bytes":1325871104,"used_in_bytes":2869755904,"free_percent":36,"used_percent":63,"actual_free_in_bytes":1519833088,"actual_used_in_bytes":2675793920},"swap":{"used_in_bytes":3538341888,"free_in_bytes":4851015680}},"jvm":{"timestamp":1431939041180,"uptime_in_millis":53453,"mem":{"heap_used_in_bytes":72258936,"heap_used_percent":6,"heap_committed_in_bytes":259522560,"heap_max_in_bytes":1046937600,"non_heap_used_in_bytes":20245832,"non_heap_committed_in_bytes":20447232
 ,"pools":{"young":{"used_in_bytes":59717112,"max_in_bytes":214827008,"peak_used_in_bytes":71630848,"peak_max_in_bytes":214827008},"survivor":{"used_in_bytes":8672008,"max_in_bytes":26804224,"peak_used_in_bytes":8912896,"peak_max_in_bytes":26804224},"old":{"used_in_bytes":3869816,"max_in_bytes":805306368,"peak_used_in_bytes":5302160,"peak_max_in_bytes":805306368}}},"threads":{"count":44,"peak_count":45},"gc":{"collectors":{"young":{"collection_count":3,"collection_time_in_millis":39},"old":{"collection_count":1,"collection_time_in_millis":49}}},"buffer_pools":{"direct":{"count":46,"used_in_bytes":6734646,"total_capacity_in_bytes":6734646},"mapped":{"count":0,"used_in_bytes":0,"total_capacity_in_bytes":0}}},"fs":{"timestamp":1431939041181,"total":{"total_in_bytes":128033222656,"free_in_bytes":4127191040,"available_in_bytes":4127191040,"disk_reads":582475,"disk_writes":327619,"disk_io_op":910094,"disk_read_size_in_bytes":3818703360,"disk_write_size_in_bytes":1967571968,"disk_io
 _size_in_bytes":5786275328,"disk_queue":"1"},"data":[{"path":"C:\\cygwin\\opt\\elasticsearch\\data\\my-application\\nodes\\0","mount":"C:\\","dev":"C:\\","type":"NTFS","total_in_bytes":128033222656,"free_in_bytes":4127191040,"available_in_bytes":4127191040,"disk_reads":582475,"disk_writes":327619,"disk_io_op":910094,"disk_read_size_in_bytes":3818703360,"disk_write_size_in_bytes":1967571968,"disk_io_size_in_bytes":5786275328,"disk_queue":"1"}]}}}},"status":200,"config":{"method":"GET","transformRequest":[null],"transformResponse":[null],"url":"http://localhost:9200/_nodes/stats/jvm,fs,os","headers":{"Accept":"application/json, text/plain, */*"}},"statusText":"OK"},{"data":{"persistent":{},"transient":{}},"status":200,"config":{"method":"GET","transformRequest":[null],"transformResponse":[null],"url":"http://localhost:9200/_cluster/settings","headers":{"Accept":"application/json, text/plain, */*"}},"statusText":"OK"},{"data":{},"status":200,"config":{"method":"GET","transformR
 equest":[null],"transformResponse":[null],"url":"http://localhost:9200/_aliases","headers":{"Accept":"application/json, text/plain, */*"}},"statusText":"OK"},{"data":{"cluster_name":"my-application","status":"green","timed_out":false,"number_of_nodes":1,"number_of_data_nodes":1,"active_primary_shards":0,"active_shards":0,"relocating_shards":0,"initializing_shards":0,"unassigned_shards":0,"number_of_pending_tasks":0},"status":200,"config":{"method":"GET","transformRequest":[null],"transformResponse":[null],"url":"http://localhost:9200/_cluster/health","headers":{"Accept":"application/json, text/plain, */*"}},"statusText":"OK"},{"data":{"cluster_name":"my-application","nodes":{"7QomAxV8S8aFUf7Zj2k6fA":{"name":"The Grip","transport_address":"inet[/135.76.235.167:9300]","host":"CZBRN0344","ip":"135.76.235.167","version":"2.0.0-SNAPSHOT","build":"${build","http_address":"inet[/135.76.235.167:9200]","os":{"refresh_interval_in_millis":1000,"available_processors":4,"cpu":{"vendor":"
 Intel","model":"Core(TM) i5-3340M CPU @ 2.70GHz","mhz":2691,"total_cores":4,"total_sockets":4,"cores_per_socket":1,"cache_size_in_bytes":-1},"mem":{"total_in_bytes":4195627008},"swap":{"total_in_bytes":8389357568}},"jvm":{"pid":5876,"version":"1.8.0_45","vm_name":"Java HotSpot(TM) Client VM","vm_version":"25.45-b02","vm_vendor":"Oracle Corporation","start_time_in_millis":1431938987770,"mem":{"heap_init_in_bytes":268435456,"heap_max_in_bytes":1046937600,"non_heap_init_in_bytes":163840,"non_heap_max_in_bytes":0,"direct_max_in_bytes":1046937600},"gc_collectors":["ParNew","ConcurrentMarkSweep"],"memory_pools":["Code Cache","Metaspace","Par Eden Space","Par Survivor Space","CMS Old Gen"]}}}},"status":200,"config":{"method":"GET","transformRequest":[null],"transformResponse":[null],"url":"http://localhost:9200/_nodes/_all/os,jvm","headers":{"Accept":"application/json, text/plain, */*"}},"statusText":"OK"}][2015-05-18 10:50:46] Error parsing cluster data:[2015-05-18 10:50:46] {}[20
 15-05-18 10:50:46] REST APIs output:[2015-05-18 10:50:46] [{"data":{"cluster_name":"my-application","master_node":"7QomAxV8S8aFUf7Zj2k6fA","blocks":{},"routing_table":{"indices":{}}},"status":200,"config":{"method":"GET","transformRequest":[null],"transformResponse":[null],"url":"http://localhost:9200/_cluster/state/master_node,routing_table,blocks/","headers":{"Accept":"application/json, text/plain, */*"}},"statusText":"OK"},{"data":{"_shards":{"total":0,"successful":0,"failed":0},"_all":{"primaries":{},"total":{}},"indices":{}},"status":200,"config":{"method":"GET","transformRequest":[null],"transformResponse":[null],"url":"http://localhost:9200/_stats/docs,store","headers":{"Accept":"application/json, text/plain, */*"}},"statusText":"OK"},{"data":{"cluster_name":"my-application","nodes":{"7QomAxV8S8aFUf7Zj2k6fA":{"timestamp":1431939046170,"name":"The Grip","transport_address":"inet[/135.76.235.167:9300]","host":"CZBRN0344","ip":["inet[/135.76.235.167:9300]","NONE"],"os":{
 "timestamp":1431939046170,"uptime_in_millis":23011,"cpu":{"sys":4,"user":7,"idle":88,"usage":11,"stolen":0},"mem":{"free_in_bytes":1329070080,"used_in_bytes":2866556928,"free_percent":36,"used_percent":63,"actual_free_in_bytes":1523339264,"actual_used_in_bytes":2672287744},"swap":{"used_in_bytes":3532722176,"free_in_bytes":4856635392}},"jvm":{"timestamp":1431939046179,"uptime_in_millis":58451,"mem":{"heap_used_in_bytes":72258936,"heap_used_percent":6,"heap_committed_in_bytes":259522560,"heap_max_in_bytes":1046937600,"non_heap_used_in_bytes":20250120,"non_heap_committed_in_bytes":20447232,"pools":{"young":{"used_in_bytes":59717112,"max_in_bytes":214827008,"peak_used_in_bytes":71630848,"peak_max_in_bytes":214827008},"survivor":{"used_in_bytes":8672008,"max_in_bytes":26804224,"peak_used_in_bytes":8912896,"peak_max_in_bytes":26804224},"old":{"used_in_bytes":3869816,"max_in_bytes":805306368,"peak_used_in_bytes":5302160,"peak_max_in_bytes":805306368}}},"threads":{"count":44,"peak_
 count":45},"gc":{"collectors":{"young":{"collection_count":3,"collection_time_in_millis":39},"old":{"collection_count":1,"collection_time_in_millis":49}}},"buffer_pools":{"direct":{"count":46,"used_in_bytes":6734646,"total_capacity_in_bytes":6734646},"mapped":{"count":0,"used_in_bytes":0,"total_capacity_in_bytes":0}}},"fs":{"timestamp":1431939046180,"total":{"total_in_bytes":128033222656,"free_in_bytes":4127191040,"available_in_bytes":4127191040,"disk_reads":582478,"disk_writes":327734,"disk_io_op":910212,"disk_read_size_in_bytes":3818715648,"disk_write_size_in_bytes":1971975680,"disk_io_size_in_bytes":5790691328,"disk_queue":"0"},"data":[{"path":"C:\\cygwin\\opt\\elasticsearch\\data\\my-application\\nodes\\0","mount":"C:\\","dev":"C:\\","type":"NTFS","total_in_bytes":128033222656,"free_in_bytes":4127191040,"available_in_bytes":4127191040,"disk_reads":582478,"disk_writes":327734,"disk_io_op":910212,"disk_read_size_in_bytes":3818715648,"disk_write_size_in_bytes":1971975680,"d
 isk_io_size_in_bytes":5790691328,"disk_queue":"0"}]}}}},"status":200,"config":{"method":"GET","transformRequest":[null],"transformResponse":[null],"url":"http://localhost:9200/_nodes/stats/jvm,fs,os","headers":{"Accept":"application/json, text/plain, */*"}},"statusText":"OK"},{"data":{"persistent":{},"transient":{}},"status":200,"config":{"method":"GET","transformRequest":[null],"transformResponse":[null],"url":"http://localhost:9200/_cluster/settings","headers":{"Accept":"application/json, text/plain, */*"}},"statusText":"OK"},{"data":{},"status":200,"config":{"method":"GET","transformRequest":[null],"transformResponse":[null],"url":"http://localhost:9200/_aliases","headers":{"Accept":"application/json, text/plain, */*"}},"statusText":"OK"},{"data":{"cluster_name":"my-application","status":"green","timed_out":false,"number_of_nodes":1,"number_of_data_nodes":1,"active_primary_shards":0,"active_shards":0,"relocating_shards":0,"initializing_shards":0,"unassigned_shards":0,"num
 ber_of_pending_tasks":0},"status":200,"config":{"method":"GET","transformRequest":[null],"transformResponse":[null],"url":"http://localhost:9200/_cluster/health","headers":{"Accept":"application/json, text/plain, */*"}},"statusText":"OK"},{"data":{"cluster_name":"my-application","nodes":{"7QomAxV8S8aFUf7Zj2k6fA":{"name":"The Grip","transport_address":"inet[/135.76.235.167:9300]","host":"CZBRN0344","ip":"135.76.235.167","version":"2.0.0-SNAPSHOT","build":"${build","http_address":"inet[/135.76.235.167:9200]","os":{"refresh_interval_in_millis":1000,"available_processors":4,"cpu":{"vendor":"Intel","model":"Core(TM) i5-3340M CPU @ 2.70GHz","mhz":2691,"total_cores":4,"total_sockets":4,"cores_per_socket":1,"cache_size_in_bytes":-1},"mem":{"total_in_bytes":4195627008},"swap":{"total_in_bytes":8389357568}},"jvm":{"pid":5876,"version":"1.8.0_45","vm_name":"Java HotSpot(TM) Client VM","vm_version":"25.45-b02","vm_vendor":"Oracle Corporation","start_time_in_millis":1431938987770,"mem":{
 "heap_init_in_bytes":268435456,"heap_max_in_bytes":1046937600,"non_heap_init_in_bytes":163840,"non_heap_max_in_bytes":0,"direct_max_in_bytes":1046937600},"gc_collectors":["ParNew","ConcurrentMarkSweep"],"memory_pools":["Code Cache","Metaspace","Par Eden Space","Par Survivor Space","CMS Old Gen"]}}}},"status":200,"config":{"method":"GET","transformRequest":[null],"transformResponse":[null],"url":"http://localhost:9200/_nodes/_all/os,jvm","headers":{"Accept":"application/json, text/plain, */*"}},"statusText":"OK"}][2015-05-18 10:50:51] Error parsing cluster data:[2015-05-18 10:50:51] {}////kopf plugin cannot connect to cluster and parse data.. 
______________________________________________________________
> Od: leonardo menezes <notifications@github.com>
> Komu: "lmenezes/elasticsearch-kopf" <elasticsearch-kopf@noreply.github.com>
> Datum: 18.05.2015 09:24
> Předmět: Re: [elasticsearch-kopf] error to parse cluster data (#277)
>
is that the whole output? seems like the body is cut. Could you paste the rest of it?
also, which version of elasticsearch are you running?

**Comment by lmenezes** [comment]
@jbrablec hum, you are running 2.0.0-SNAPSHOT... I'm only developing/testing to latest stable release(1.5.X). I will at some point start testing things against 2.0, but not in the very near future. sorry :)
