### ISSUE TITLE
Errors with pagination.html and nodex.html

### ISSUE THREAD

**Issue by elvarb** [lmenezes/elasticsearch-kopf#278]
I have Elasticsearch behind a reverse proxy and access Kopf from a dedicated web server that queries the reverse proxy. This means I can not see all indices in the cluster, as in I can not go through them, I only see the first "page" but I can search for all others. The nodes page shows up empty.

When I load the cluster stat I get this in the Chrome console

GET http://hostname/mgmt/kopf/partials/directives/pagination.html 404 (Not Found)b @ angular-route.js:6m @ angular-route.js:6$get.f @ angular-route.js:6(anonymous function) @ angular-route.js:6$get.l.$eval @ angular-route.js:6$get.l.$digest @ angular-route.js:6$get.l.$apply @ angular-route.js:6l @ angular-route.js:6S @ angular-route.js:6D.onload @ angular-route.js:6
angular-route.js:6 Error: [$compile:tpload] http://errors.angularjs.org/1.3.14/$compile/tpload?p0=.%2Fpartials%2Fdirectives%2Fpagination.html
    at Error (native)
    at http://hostname/mgmt/kopf/dist/lib.js:12:417
    at http://hostname/mgmt/kopf/dist/lib.js:142:261
    at http://hostname/mgmt/kopf/dist/lib.js:118:24
    at l.$get.l.$eval (http://hostname/mgmt/kopf/dist/lib.js:131:309)
    at l.$get.l.$digest (http://hostname/mgmt/kopf/dist/lib.js:128:400)
    at l.$get.l.$apply (http://hostname/mgmt/kopf/dist/lib.js:132:64)
    at l (http://hostname/mgmt/kopf/dist/lib.js:87:175)
    at S (http://hostname/mgmt/kopf/dist/lib.js:91:303)
    at XMLHttpRequest.D.onload (http://hostname/mgmt/kopf/dist/lib.js:92:321)

And a the same error for nodes.html.

When I view the files that are supposed to be missing the angular app gives me this error

{"error":"RemoteTransportException[[ESServer03][inet[/192.168.0.3:9300]][indices:admin/get]]; nested: IndexMissingException[[pagination.html] missing]; ","status":404}

Why is it querying port 9300 and not 9200?

What is kopf trying to query when this fails?

This used to work fine before the 1.5 version.

I installed kopf directly as a plugin on one of the client nodes and there everything is working. So guessing it has something to do with the reverse proxy

**Comment by lmenezes** [comment]
@elvarb hey :)
yes, I'm guessing it is related to the reverse proxy setup:
```
{"error":"RemoteTransportException[[ESServer03][inet[/192.168.0.3:9300]][indices:admin/get]]; nested: IndexMissingException[[pagination.html] missing]; ","status":404}
```
the requests to fetch the html pages seem to be going directly to elasticsearch instead of the _plugins folder.

Which version of kopf are you using? If you are on most recent version, if you could copy the contents of the log?
![screenshot 2015-06-01 18 10 06](https://cloud.githubusercontent.com/assets/750074/7917315/c1716328-0889-11e5-991d-d6e84ebfd305.png)

**Comment by elvarb** [comment]
Clicking on the cog wheel tells me its version 1.5.3

**Comment by lmenezes** [comment]
@elvarb could you tell me how to reproduce your setup?

**Comment by elvarb** [comment]
@lmenezes 

IIS ARR is used for reverse proxy

dns.local/ is the location of kibana3
dns.local/es/ is the location of elasticsearch server pool
dns.local/kopf/ is the location of kopf

When starting kopf from that URL it is set to connect to http://dns.local/es/

All this is done because of kerberos authentication problems when javascript tries to run against a different dns name where authentication is also needed, simply does not work (or did not when I tested it last time)

**Comment by lmenezes** [comment]
@elvarb hum, sorry, I have no experience with IIS ARR or the means to try this out. 
I have just added some info to https://github.com/lmenezes/elasticsearch-kopf/blob/develop/README.md into how to run kopf behind a reverse proxy. Hopefully that helps you somehow?

**Comment by elvarb** [comment]
I will have to take a look at how the root path config is in my setup, that could very likely be the problem

**Comment by lmenezes** [comment]
@elvarb is this still an issue?

**Comment by lmenezes** [comment]
I will close this for now, if this is still a problem, please open another issue.
