### ISSUE TITLE
Switching to URL with basic auth

### ISSUE THREAD

**Issue by davidearl** [lmenezes/elasticsearch-kopf#280]
I have a test site with no authentication and http on port 9200 (only accessible internally, as in http://192.168.0.2:9200) and what will become a live system which uses basic auth over https (as in https://user:password@example.com/ )

I could switch to the live site the first time, then I switched back, but then I tried to switch to the live site again but I can't because it is in the previous hosts list, but with the authentication removed. Its presence there seems to prevent me from pasting the full URL including the authentication and pressing enter. So I'm stuck.

**Comment by lmenezes** [comment]
@davidearl could you paste the contents of the log? the one at the bottom of the page :)

**Comment by davidearl** [comment]
Unfortunately that contains the password among other confidential things.

However, if I select the site from the menu, it shows 
{"error":"Authorization is required to perform this request. Please provide credentials, or contact support@bonsai.io for assistance.","status":401}

as you might expect I suppose, but it makes it pointless to have it on the menu.

If I paste in the complete URL including the credentials, it has among the output:
[2015-06-05 11:03:34] Error parsing cluster data:
[2015-06-05 11:03:34] {}

which is presumably why I then see nothing. It has the full output below, but again this has undisclosable details in it.

The remote site is at bonsai.io. You can create a free cluster there, so I imagine you could reproduce it easily by doing that.

The odd thing is, I definitely saw it once!

**Comment by lmenezes** [comment]
@davidearl can you try adding an extra / at the of the url?
Like, connecting to http://localhost:9200// for example?
