### ISSUE TITLE
Error executing request for ES 1.5.2

### ISSUE THREAD

**Issue by gboanea** [lmenezes/elasticsearch-kopf#281]
Kopf could not connect to the ES cluster.
Log:
```
Elasticseach connection:
{"host":"http://127.0.0.1:48032","withCredentials":false}
Error executing request:
{"method":"GET","transformRequest":[null],"transformResponse":     [null],"url":"http://127.0.0.1:48032/","data":{},"params":{},"headers":{"Accept":"application/json, text/plain,    */*"}}
REST API output:
```
ES version: 1.5.2
Kopf version: 1.5.3

Everything worked fine for ES 1.3.4.

**Comment by lmenezes** [comment]
could you post the content of the REST API output? or there was none?

**Comment by gboanea** [comment]
There was no REST API output

**Comment by lmenezes** [comment]
What do you get by:
curl -XGET http://127.0.0.1:48032 
?

**Comment by gboanea** [comment]
{
  "status" : 200,
  "name" : "node4",
  "cluster_name" : "cluster00",
  "version" : {
    "number" : "1.5.2",
    "build_hash" : "62ff9868b4c8a0c45860bebb259e21980778ab1c",
    "build_timestamp" : "2015-04-27T09:21:06Z",
    "build_snapshot" : false,
    "lucene_version" : "4.10.4"
  },
  "tagline" : "You Know, for Search"
}

**Comment by gboanea** [comment]
curl 'http://127.0.0.1:48032/_cluster/health?pretty=true'
{
  "cluster_name" : "cluster00",
  "status" : "green",
  "timed_out" : false,
  "number_of_nodes" : 4,
  "number_of_data_nodes" : 4,
  "active_primary_shards" : 5,
  "active_shards" : 10,
  "relocating_shards" : 0,
  "initializing_shards" : 0,
  "unassigned_shards" : 0,
  "number_of_pending_tasks" : 0
}

**Comment by lmenezes** [comment]
ok. I think it's the CORS issue: https://github.com/lmenezes/elasticsearch-kopf/issues/195
let me know :)

**Comment by gboanea** [comment]
Yep, this was the issue.
Thank you very much :)

**Comment by lmenezes** [comment]
np :)
