### ISSUE TITLE
Possible to bring back hostname on the nodeview?

### ISSUE THREAD

**Issue by Dinoshauer** [lmenezes/elasticsearch-kopf#282]
Hey, I really liked the feature that showed the hostname of the node, that's how I navigate our nodes as we have a bunch of nodes in it it's easier to remember names than internal ip adresses.

Would it be possible to do a config option or something that would show it like in the old days?

https://github.com/lmenezes/elasticsearch-kopf/commit/253093401158ac5aa0d9c40d33b3c7d9852c4f3c - is the commit that made the change

*EDIT:* Would be cool with a button to copy the hostname even!

**Comment by MonnyA** [comment]
+1. At the very least it could appear as a basic tooltip on mouse hover on the IP or something.

**Comment by lmenezes** [comment]
indeed having the hostname normally makes more sense than the ip. 
In my case, the node name and the host name are the same(not exactly, but knowing one I know the other), so this was never really a concern for me. And some people seemed to need the ip.
I had in my pipeline to have an "extended view/compact view" toggle, so will just ship this together.
