### ISSUE TITLE
ES 2.0.x support 

### ISSUE THREAD

**Issue by apatrida** [lmenezes/elasticsearch-kopf#284]
Adding this ticket to track 2.0.x support, BETA was announced as "soon"

There is another ticket #277 that talks about the error related to this, but the title isn't very useful for that issue so people won't see it. 

Dropping this one here, so people can find it, know the status, and not annoy anyone too much by asking "WTF, where is it?!?"

**Comment by lmenezes** [comment]
since v1.5.7, kopf should work with both 1.X and 2.0(as long as nothing changes on the 2.X branch)
