### ISSUE TITLE
Acessing kopf returns blank page with syntax error on Safari and Chrome

### ISSUE THREAD

**Issue by splashx** [lmenezes/elasticsearch-kopf#293]
I'm using the latest version of Safari and Chrome and after pointing to http://server_ip:8080/kopf/ I get a blank page:

![blank page]
(http://s7.postimg.org/g6c09b6hn/Screen_Shot_2015_07_29_at_11_34_35_PM.png)

I've followed the installation steps in the README (reverse proxy). 

Kopf is installed in a client node (node.master and node.data both set to false) - could that be the issue?

**Comment by splashx** [comment]
When clicking on the lower right corner on kopf.js, this is the output:
![Imgur]
(http://i.imgur.com/orXiTHU.png)

**Comment by lmenezes** [comment]
which version of elasticsearch and kopf are you using?

**Comment by splashx** [comment]
Because the nginx config was being fed to the server using "cat", it was my mistake to not escape the $ signs. Therefore the configuration proposed on README ended up like this:

`rewrite                 ^/es(.*) / break;`

instead of:

`rewrite ^/es(.*) /$1 break;`

My mistake.

**Comment by lmenezes** [comment]
ah, glad it works :)
