### ISSUE TITLE
When loading latest version from local file, doesn't appear to work in Chrome/Opera

### ISSUE THREAD

**Issue by geekpete** [lmenezes/elasticsearch-kopf#294]
Blank page when loading from local filesystem, but seems to work fine if loading from an elasticsearch node when loaded as a site plugin.

**Comment by lmenezes** [comment]
Yeah, this is a long known issue(https://github.com/lmenezes/elasticsearch-kopf/blob/master/README.md#run-locally) caused by AngularJS.

As I assume this represents no problem for most people, never looked further into it.
