### ISSUE TITLE
Links on Screenshots section of README.md file are broken

### ISSUE THREAD

**Issue by krinkere** [lmenezes/elasticsearch-kopf#295]
For example, cluster overview points to 
https://github.com/lmenezes/elasticsearch-kopf/blob/master/imgs/cluster_view.png
which gives 404

**Comment by lmenezes** [comment]
true, broke that when adapting kopf to elastic 2.0. will have this fixed in the afternoon

**Comment by krinkere** [comment]
Thank you sir!
