### ISSUE TITLE
show node name next to cluster name

### ISSUE THREAD

**Issue by muelli** [lmenezes/elasticsearch-kopf#301]
I have several ES instances open and I get confused which interface is for which node. I think it'd be good if kopf shows the node's name. Right now, kopf shows the cluster's name in the top bar. Maybe adding the node's name there is an option.
I'm using 1.5.4.

**Comment by up-town-down** [comment]
Do you, mean in the browser tab/title bar or the top bar within the pane? The latter is already true...

**Comment by muelli** [comment]
I mean the latter.  But the former is also fine. So far, I see this:
![screenshot from 2015-09-15 09 49 12](https://cloud.githubusercontent.com/assets/322807/9870767/2200d4be-5b8f-11e5-9ea9-5c0fba5d7d99.png)

and I can't locate the node's name anywhere on the page :-/
If it is buried somewhere on the page, I'd appreciate if it was made a bit more visible.

**Comment by up-town-down** [comment]
Ah, my apologies, I have a dns alias with the node's name in it so top right where you have ip/port I have node name :)

**Comment by lmenezes** [comment]
kind of tight on time right now, but this is small enough for me to find sometime this week :)
