### ISSUE TITLE
[feature request]Support include_aliases option when restoring snapshot

### ISSUE THREAD

**Issue by niu-lin** [lmenezes/elasticsearch-kopf#302]
include_aliases option can be set to true/false to control whether the alias should also be restored with snapshot. This is enabled by kopf by default and cannot changed.  
However, when restoring the snapshot, we want to prevent alias to be restored too. Can I request to add a feature into kopf so that we can select whether we want to restore alias while restoring from snapshots?

**Comment by lmenezes** [comment]
sure :+1:

**Comment by niu-lin** [comment]
Thank you very much!
