### ISSUE TITLE
Shutdown Node functionality

### ISSUE THREAD

**Issue by allthedrones** [lmenezes/elasticsearch-kopf#304]
I noticed that the *shutdown node* functionality has been removed recently, and there doesn't seem to be an issue # or release notes around the change. I'm hoping we can get some better insight into the reason(s) for removing the functionality (which my colleagues and I found pretty useful)? I'd be willing to try and work up a PR to make the feature configurable via `kopf_external_settings.json` if you're open to it. Thanks for all the work on such a great tool!

**Comment by up-town-down** [comment]
Just a guess but as elastic are completely removing the shutdown api in elasticsearch 2.0 it'll be redundant pretty soon so that's probably why it's gone...

**Comment by lmenezes** [comment]
@allthedrones yes, @up-town-down is right. 2.0 removes the API, so it's not possible to keep the functionality. Btw, this was only removed on the master/2.0 branch, so if you stick with the latest 1.X version, this should still be available.

**Comment by allthedrones** [comment]
Ah, makes sense. Thanks for the clarification.
