### ISSUE TITLE
Apache Rewrite

### ISSUE THREAD

**Issue by pbmsys** [lmenezes/elasticsearch-kopf#307]
Hi.
I Wondered if anybody have made kopf work with an apache reverse proxy?
i cant hit the right conversion from the NGINX rewrite rules in the README example.

My proxy is an Apache Server 2.4.6 on Server A which proxies to ES Cluster on Server B.

/Peter

**Comment by Nefelim4ag** [comment]
Hi, may be it's can help you with this is what we used with nginx
We have several node in cluster, and only 2 'potential' master nodes, i've just install addons on it, and proxy it with nginx, and its work perfectly

Example:
upstream elasticsearch {
        least_conn;
        server 172.0.0.39:9200;
        server 172.0.0.41:9200;
        keepalive 64;
}

server {
        listen      80;
        server_name es.itransition.corp;
        return 301 https://$server_name$request_uri;  # enforce https
}

server {
        listen                *:443;
        server_name es.itransition.corp;

        ssl on;
        ssl_certificate         /etc/ssl/private/es.pem;
        ssl_certificate_key     /etc/ssl/private/es.key;

        access_log      /var/log/nginx/es.access.log;

        location / {
                proxy_connect_timeout   600s;
                proxy_read_timeout      600s;
                proxy_send_timeout      600s;

                proxy_pass http://elasticsearch;
        }

        auth_ldap "Ldap_Group";
        auth_ldap_servers EXAMPLE.COM;
}

server {
        listen 127.0.0.1:9200;
        location / {
                proxy_connect_timeout   600s;
                proxy_read_timeout      600s;
                proxy_send_timeout      600s;

                proxy_pass http://elasticsearch;
        }
}

**Comment by pbmsys** [comment]
@Nefelim4ag
Thank you for your quick response, how does your kopf_external_settings.json look like to manage this?

**Comment by Nefelim4ag** [comment]
@pbmsys,
i'dont change something, just do "plugin install ..." on 2 nodes.
I.e. standart:
# cat /usr/share/elasticsearch/plugins/kopf/_site/kopf_external_settings.json
{
    "elasticsearch_root_path": "",
    "with_credentials": false,
    "theme": "dark",
    "refresh_rate": 5000
}

**Comment by pbmsys** [comment]
@Nefelim4ag 
So you are using an NGINX on the ES hosts as well?

**Comment by Nefelim4ag** [comment]
Nope, i've a separeted host (nginx based) with kibana and Es plugins on the ES node, i use iptables, to restrict access

**Comment by Nefelim4ag** [comment]
Access to 9300 port on es*, on nginx, i've use ldap auth

**Comment by up-town-down** [comment]
Hopefully you've had enough info to fix your nginx config, I personally found that a bit hard to get working, when I tried.  But if you're still looking at Apache I used an Apache Reverse Proxy with help from a colleague, I don't have the exact config to hand but it's very similar to the one here: https://www.digitalocean.com/community/tutorials/how-to-use-apache-http-server-as-reverse-proxy-using-mod_proxy-extension and works a treat

**Comment by pbmsys** [comment]
I have tried configured it as the following:
RewriteEngine on
LogLevel alert rewrite:trace6
RewriteRule ^/kopf/(.*)$ http://localhost:9200/_plugin/kopf/$1 [P]
ProxyPassReverse /kopf/ http://localhost:9200/kopf


But i recieve an error on kopf cant connect to my host at port 80.
Cant seem to work out why
Any insight?

**Comment by up-town-down** [comment]
Apologies I'm on holiday at the moment, but I will try and grab the configuration from the office on Monday if you're still stuck!

**Comment by lmenezes** [comment]
hey @pbmsys
what is your intended setup? Maybe I can help :)

**Comment by pbmsys** [comment]
Hey @lmenezes 
Sorry i forgot to close this issue. I fixed the issue in apache after some work :)

**Comment by pbmsys** [comment]
The relevant configuration i apache :)

############################ KOPF ############################
        RewriteCond %{LA-U:REMOTE_USER} !^$
	RewriteRule ^/kopf/(.*)$ http://localhost:9200/_plugin/kopf/$1 [P]
	ProxyPassReverse /kopf http://localhost:9200/_plugin/kopf

############################ Elastic ############################
	RewriteRule ^/es/(.*)$ http://localhost:9200/$1 [P]
	ProxyPassReverse /es/ http://localhost:9200/

**Comment by lmenezes** [comment]
@pbmsys great then, I ended up with something similar. Will add that to the docs in case its useful to somebody else.

**Comment by up-town-down** [comment]
Sorry, I totally forgot to post the file, but that's pretty much exactly what I had, glad you got it sorted!
