### ISSUE TITLE
Load average missing and misreported CPU %

### ISSUE THREAD

**Issue by johnlauck** [lmenezes/elasticsearch-kopf#311]
We're running kopf 1.5.7-SNAPSHOT on AWS (r3 instances) with ES 1.4.0.  The load average is missing and it looks like CPU % only reports stats from one core. 

Our previous platform didn't have this issue.  Load average was always visible and CPU % looked like it was divided by the number of cores.

CPU and load stats return fine from the ES api. 

Screenshot:

<img width="1544" alt="kopf_production2-replicated_" src="https://cloud.githubusercontent.com/assets/58893/10309878/f6c775bc-6c0c-11e5-89b1-2712476498b2.png">

Has anyone else seen this issue?

**Comment by whizz** [comment]
I am seeing the same thing in v2.0.0-SNAPSHOT on ES 1.7.2.

**Comment by lmenezes** [comment]
hey,
kopf 2.0 is not compatible with 1.X ES versions(es 2.0 just doesnt offer this metrics anymore).
For 1.X es, you should use latest from 1.0 branch(v1.5.7 atm).

hope this helps 😊

**Comment by whizz** [comment]
Oh, right. Sorry, my bad. The 1.5.7 on ES 1.7.2 works correctly. Thanks, Leonard, for a quick reply and thank you for your excellent work on Kopf.

**Comment by lmenezes** [comment]
@johnlauck are you sure you are running 1.5.7-SNAPSHOT? this really looks like a 2.0 x 1.X ES issue.

**Comment by johnlauck** [comment]
We're hosting on a 3rd party host that has told us the version is `1.5.7-SNAPSHOT`.  Is there a way to verify the version from the kopf without access to the source or local file system?

**Comment by lmenezes** [comment]
@johnlauck yes, just check the cog wheel on the right side of the navigation bar. the popup should display the version :)

**Comment by johnlauck** [comment]
Bingo!  `v2.0.0-SNAPSHOT` 

Thanks @lmenezes!
