### ISSUE TITLE
High CPU %

### ISSUE THREAD

**Issue by mathewmeconry** [lmenezes/elasticsearch-kopf#312]
HI

When I check my CPU usage on each node I see that it uses over 300%.
![image](https://cloud.githubusercontent.com/assets/4057473/10478307/d3af92a2-725c-11e5-9aef-e4ed9db2988c.png)

**Comment by mathewmeconry** [comment]
sorry forgot to mention that I'm using V2.0.0-SNAPSHOT

**Comment by lmenezes** [comment]
I assume you are using ES 1.X with Kopf 2.0-SNAPSHOT. If that is the case, you should use v1.5.7, since 2.0-Snapshot is targeted at 2.0 release and has a few things that won't work with pre 2.0.

As for the CPU, what is the problem exactly? Do you see a different value using top?

**Comment by xros** [comment]
I shoot my admiration to this project. This UI looks great. And I am alternating from ElasticSearchHQ. :+1:

**Comment by mathewmeconry** [comment]
You're right I'm using 1.7.3.
It works now.

Thanks

**Comment by lmenezes** [comment]
@xros thanks, this is very kind :)
