### ISSUE TITLE
Wrong hostname

### ISSUE THREAD

**Issue by cp2587** [lmenezes/elasticsearch-kopf#313]
Hello,

First let me thank you for you're amazing work in this plugin. We are using the 1.5.8 version and it seems like the hostname int '#!/cluster' route is not correct: it shows 'localhost' for every node even if they all have a correctly set different hostname - see screenshot
![hostname_error](https://cloud.githubusercontent.com/assets/5306537/10638813/170ed962-780d-11e5-8502-658eb8e2521a.png)

**Comment by lmenezes** [comment]
@cp2587  thanks :)

Which version of ES are you using?
Also, could you paste the response from executing:
```
curl -XGET http://YOURHOST:PORT/_nodes/_all/host
```

Perhaps your nodes really have hostname = localhost. For me this is working fine :)

**Comment by cp2587** [comment]
I do have host = localhost ! But when i run hostname, i get the right name... Do you know how does ES select the hostname ?

**Comment by lmenezes** [comment]
@cp2587 not really sure, but perhaps your JVM was started before setting the hostname?
