### ISSUE TITLE
Kopf in Chrome fails to reconnect when loading from cold

### ISSUE THREAD

**Issue by xrl** [lmenezes/elasticsearch-kopf#318]
When loading Kopf it seems to remember my usual host but it fails to connect

![image](https://cloud.githubusercontent.com/assets/693059/10772795/037dd32e-7cb5-11e5-839b-e1015c96957c.png)

The work around is to click on the gear on the right and choose the host again:

![image](https://cloud.githubusercontent.com/assets/693059/10772815/1cdcc28a-7cb5-11e5-902e-e5bbe0ed7127.png)

Could it be my style of reverse proxying the ES server? "http://10.69.8.55/es/"

**Comment by lmenezes** [comment]
@xrl It's not that kopf remembers your usual host, it just tired to connect the server serving the HTML files(notice the missing /es/).

I don't particular use kopf together with a proxy, but someone that does made it work(https://github.com/lmenezes/elasticsearch-kopf/issues/307)

hope this helps you!

**Comment by xrl** [comment]
Kopf does work with the reverse proxy. Just in terms of ergonomics it's not fun to have an error popup everytime I load the Kopf app.

**Comment by lmenezes** [comment]
@xrl yes, I know. My point was the configuring it properly this shouldn't happen. You can set a "base" url for kopf, for example for your case, appending an "/es" to it -> https://github.com/lmenezes/elasticsearch-kopf/blob/master/_site/kopf_external_settings.json

Hope this solves your problem :)

**Comment by lmenezes** [comment]
@xrl is this still an issue?

**Comment by lmenezes** [comment]
@xrl will take this as not an issue any longer.
