### ISSUE TITLE
URL Encode for indexes with special characters

### ISSUE THREAD

**Issue by Maran123** [lmenezes/elasticsearch-kopf#324]
Hi, 

Minor bug found

How to:
Create index with name logstash-{special} try to view settings / mappings for index.

Expectation:
Shows settings / Mappings

Result:
Error index not found

Analysis
From what I can see this is due to requests not being URL encoded.
Ex. curl 'http://localhost:9200/logstash-{special}/' will not work
But curl 'http://localhost:9200/ logstash-%7Bspecial%7D' works

running kopf 1.5.3

**Comment by lmenezes** [comment]
@Maran123 this has been fixed in kopf 1.5.6. But if you upgrade, I'd recommend 1.6.1 :)
