### ISSUE TITLE
Error parsing REST API data 

### ISSUE THREAD

**Issue by abournier** [lmenezes/elasticsearch-kopf#329]
Hello,

I can actually see the Kopf dashboard, but with an error:

```
[2015-12-08 12:27:24] Elasticseach connection:
[2015-12-08 12:27:24] {"host":"http://kopf.app.com:80","withCredentials":false}
[2015-12-08 12:27:24] Error parsing REST API data:
[2015-12-08 12:27:24] {"line":4571,"column":47,"sourceURL":"http://kopf.app.com/dist/kopf.js"}
[2015-12-08 12:27:24] REST API output: "<!DOCTYPE html>\n<html lang=\"en\" ng-app=\"kopf\" ng-controller=\"GlobalController\">\n <head>\n <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\"/>\n <meta charset=\"utf-8\">\n 
```

My proxy config, with some credentials, is:

```
server {
    listen 80;
    server_name kopf.app.com;

    auth_basic "Kopf Authentication";
    auth_basic_user_file /etc/nginx/.htpasswd;

    location / {
        proxy_pass http://localhost:9200;
        rewrite ^/(.*) /_plugin/kopf/$1 break;
    }
}
```

What did I miss ?
Note that elasticsearch is running with a proxy, credentials and SSL.

**Comment by lmenezes** [comment]
@abournier Take a look at the readme -> https://github.com/lmenezes/elasticsearch-kopf#kopf-behind-a-reverse-proxy

You will need to set a custom "root path" for ES(on kopf) and add the corresponding rule to deal with this.

hope this helps :)

**Comment by lmenezes** [comment]
@abournier could you get this to work?

**Comment by abournier** [comment]
No, because I changed to a dedicated sever these days, so ES and main app are on the same server now. So I access ES with locahost and port. So how to get kopf working on this condition ? Does I need a proxy too ? Or just change the root path ?

**Comment by lmenezes** [comment]
Do you have kopf now installed on the server? if so, just append /_plugin/kopf to the ES url and it should work fine.

**Comment by abournier** [comment]
But I don't have ES url, ES is just running on the localhost with port 9200.

**Comment by lmenezes** [comment]
http://localhost:9200/_plugin/kopf should work then(I'm assuming you installed the plugin on your ES instance)

**Comment by abournier** [comment]
No because it's a remote server. For example, my Rails/MySQL app access the ES instance via locahost and port 9200, but I can't access localhost from a browser (of course - because it's remote, not local). SO, does I need a proxy in this case ? Is-it possible to access kopf via http://my-server-ip:9200/_plugin/koft ?

**Comment by lmenezes** [comment]
you don't need a proxy for that, as long as the ip:port is reachable. so yes, http://my-server-ip:9200/_plugin/kopf should work

**Comment by abournier** [comment]
Yes, but it doesn't work. Note that ES is set to be working only on localhost in conf (not accessible via my ip for security reasons). And port 9200 is visible in my IPTables.

**Comment by lmenezes** [comment]
if its not accessible by ip from the outside, then yeah, you will need a proxy.

**Comment by abournier** [comment]
OK. Thanks. Will try soon.

**Comment by lmenezes** [comment]
@abournier did you have the chance to test it?
