### ISSUE TITLE
Adding more disk stats in node stats

### ISSUE THREAD

**Issue by shahar-fleischman** [lmenezes/elasticsearch-kopf#331]
Hi,

Is it possible to add:
disk_queue 
disk_reads
disk_writes

To the node stats ?
Either combined, or per data device.
The node stats in kopf is very helpful, but i think disk perf info is missing.

Thank you.

**Comment by lmenezes** [comment]
@shahar-fleischman I think at the moment its not really possible to add these metrics. Sometime ago Sigar was removed from ES, and these metrics(and many others), were fetched through it. sorry :(
