### ISSUE TITLE
connecting to a different host

### ISSUE THREAD

**Issue by evvo1961** [lmenezes/elasticsearch-kopf#336]
im trying to connect to our cloud elasticsearch provider but when i click on the cog (top right of screen) i am not able to remove the existing localhost:9200 address...

it cant be selected or deleted, just shows a blue line around the textbox...

if i do overwrite the existing url with my new url and click save i get an error msg - error updating cluster settings....

how do i update this field?

**Comment by lmenezes** [comment]
@evvo1961 UX failure :)
this localhost:9200 is not really a text, its just the "hint" text(which is horribly coloured).

Just type whatever you want there and hit enter, should to the trick :)
