### ISSUE TITLE
Kopf Version Compatibility

### ISSUE THREAD

**Issue by andrewduch** [lmenezes/elasticsearch-kopf#340]
Hi,

Looking for some guidance on what versions of Elastic are compatible with Kopf 1.6.1 (the latest).

I've tried 1.7.4 and 1.7.3 w/ 1.6.1 but both say "Upgrading to newest supported version is recommended"

Thanks!
Andrew

**Comment by jamescarr** [comment]
:+1: I get this problem too... i tried with both 1.6.1 and 1.6.2 and both bug me with the very annoying notification below non-stop. It actually works fine but the constant animation of that notice drives everyone away. 


<img width="558" alt="screen shot 2016-01-28 at 3 04 29 am" src="https://cloud.githubusercontent.com/assets/45389/12639777/dfad3b38-c56b-11e5-8d0f-bd18e9857075.png">

**Comment by lmenezes** [comment]
@andrewduch Humm... I'm trying out this with kopf 1.6.2 and ES 1.7.3, and I don't get this issue.
Sorry for asking, but are you both sure you are not running ES 2.X?

If not, could you try downloading a fresh copy of ES(1.X) and installing the latest from 1.X?
```
[10:10] leo:elasticsearch-1.7.3/ $ ./bin/plugin install lmenezes/elasticsearch-kopf/1.0
```

**Comment by lmenezes** [comment]
alternatively, I should really add the cluster version somewhere visible, as this might help with issues like this :)

**Comment by andrewduch** [comment]
@lmenezes That worked. I was using `install lmenezes/elasticeasrch-kopf/1.6.2` ... switching to 1.0 worked. Thanks!

**Comment by jamescarr** [comment]
Wow... why is that?

**Comment by lmenezes** [comment]
@jamescarr basically the install takes either a version(tag) or a branch.
version/tags have a v prefix, so it should be v1.6.2 ;)

**Comment by lmenezes** [comment]
@jamescarr was this also the case for you?

**Comment by jamescarr** [comment]
Yep! Changing it to v1.6.2 worked.

**Comment by lmenezes** [comment]
@jamescarr great :)
As soon as I find time, I will try to both improve the README and also, improve this feedback message to actually inform cluster version and plugin version. This might save headache for others as well.
