### ISSUE TITLE
Support es-1.7?

### ISSUE THREAD

**Issue by Nalum** [lmenezes/elasticsearch-kopf#343]
Will support be added for es-1.7?

**Comment by lmenezes** [comment]
it is already supported, you are likely just running kopf v2, which doesn't support 1.X.

Try installing latest from 1.X branch :)

**Comment by Nalum** [comment]
Ah. Thanks I'll try get that sorted today.

**Comment by apatrida** [comment]
well, kopf 1.6.2 says it doesn't support ES 1.7.6
