### ISSUE TITLE
Error executing request

### ISSUE THREAD

**Issue by BentCoder** [lmenezes/elasticsearch-kopf#346]
Hi,

This is what I get from my ES:
```
# http://192.168.0.56:9201
# curl -X GET 192.168.0.56:9201

{
  "status" : 200,
  "name" : "Gregor Shapanka",
  "cluster_name" : "elasticsearch",
  "version" : {
    "number" : "1.7.4",
    "build_hash" : "0d3159b9fc8bc8e367c5c40c09c2a57c0032b32e",
    "build_timestamp" : "2015-12-15T11:25:18Z",
    "build_snapshot" : false,
    "lucene_version" : "4.10.4"
  },
  "tagline" : "You Know, for Search"
}
```

I access to KOPF via `http://localhost:9000/_site/#!/cluster` and change the host to `http://192.168.0.56:9201/` in settings. The info bar reads as follows so nothing appears in the page.

```
[2016-03-05 15:59:46] Elasticseach connection:
[2016-03-05 15:59:46] {"host":"http://192.168.0.56:9201","withCredentials":false}
[2016-03-05 15:59:46] Error executing request:
[2016-03-05 15:59:46] {"method":"GET","transformRequest":[null],"transformResponse":[null],"url":"http://192.168.0.56:9201/","data":{},"params":{},"headers":{"Accept":"application/json, text/plain, */*"}}
[2016-03-05 15:59:46] REST API output:
```

**Comment by lmenezes** [comment]
hey @BentCoder 
I assume you don't have CORS enabled on ES. Check https://github.com/lmenezes/elasticsearch-kopf/issues/195

**Comment by BentCoder** [comment]
@lmenezes Thanks for the prompt answer,

I have two yml files as shown below:

```
/Users/bentcoder/elasticsearch-1.7.4/config/elasticsearch.yml
/usr/local/etc/elasticsearch/elasticsearch.yml
```

I don't see any `cors` keyword in files above so which one of [these](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-http.html) should go to which file above?

**Comment by up-town-down** [comment]
See https://www.elastic.co/guide/en/elasticsearch/reference/2.2/breaking_20_setting_changes.html#_cors_allowed_origins for more detail on setting up cors

It needs to go in the config file you're using to run it! if you're not supplying this on the command line it'll probably be the second one if you have es installed as a service. but if your running that local copy in your users folder, then it might be that one - that you'll have to figure out for yourself!

**Comment by BentCoder** [comment]
I solved the issue by going for https://github.com/lmenezes/elasticsearch-kopf#installing-on-an-elasticsearch-instance instead. I now can access it via `http://192.168.0.56:9201/_plugin/kopf/#!/cluster`
