### ISSUE TITLE
Working with aliases

### ISSUE THREAD

**Issue by jancoonder** [lmenezes/elasticsearch-kopf#347]
Hello,

I run into problem with aliases. A while ago I have setup ES 2.2.0 environment and installed KOPF version 2.0.1 as plugin. When I try to create/delete alias for any index, it seems to run, the success message is shown. But if I reload the alias management page, or do manual JSON request toward ES, the aliases remains unchanged. Also LOG doesn't show any error.

can you point me towards what may be wrong?

**Comment by lmenezes** [comment]
@jancoonder hey :)
I think you are not really saving the aliases operations you are doing.

The aliases screen allows you to add/remove multiple aliases(left section), and then execute everything as a single operation(right section, red button). 

hope this helps!

**Comment by jancoonder** [comment]
yes, that's it :+1: 
I was distracted by the success message :)
thanks :)
