### ISSUE TITLE
Alias config

### ISSUE THREAD

**Issue by adrianlop** [lmenezes/elasticsearch-kopf#350]
Hi,

I think it would be nice to have a button to add/remove alias in the index dropdown:

![image](https://cloud.githubusercontent.com/assets/2879742/13918598/c18f5b32-ef68-11e5-8129-5e08ad1aa8ba.png)

great plugin btw, thank you!

**Comment by up-town-down** [comment]
umm, it's right there on the main menu... https://github.com/lmenezes/elasticsearch-kopf/blob/master/imgs/aliases.png

**Comment by adrianlop** [comment]
oops... thanks @up-town-down !
