### ISSUE TITLE
use watermark settings to determine warning/critical disk space level indicator color

### ISSUE THREAD

**Issue by TheCase** [lmenezes/elasticsearch-kopf#351]
enhancement request: 

if the watermarks differ from default, use the watermark settings to determine warning (low, yellow) and critical (high, red) color for disk space indicator graphic under node in cluster view.

It appears that you are currently using a hard-coded low default of 75% to trigger the change from green to red.

**Comment by lmenezes** [comment]
hey @TheCase 
I'm no longer actively developing kopf, as the new elasticsearch version won't be supporting site plugins anymore.
I'm working on an app to replace kopf(https://github.com/lmenezes/cerebro), and even though it's not at the moment feature complete(when compared to kopf), it should soon be. I will take this into account in this other app :)
