### ISSUE TITLE
Option to turn off the log

### ISSUE THREAD

**Issue by pricecarl** [lmenezes/elasticsearch-kopf#353]
Hey,

A question more than a an issue - Is there is any option to turn off the log at the bottom of the kopf screen?

The reason I ask is because I have installed shield on my ES cluster and when a user without the required permissions tries to access kopf the log displays the extract permissions they need.

It would be much better if I could remove the log entirely so it doesn't give out the needed permissions. 
This could be considered a security problem.

**Comment by lmenezes** [comment]
hey,

hum.. the way I see if they can see this information through kopf, they can also see it without kopf. in this case, I'd say kopf only might make this "easier" to see.
As for removing the log... I'm not really continuing development on kopf, as it will no longer be supported as it is on next major ES release. I'm currently working on a replacement, and hope it will be available before kopf becomes unusable on ES :)

**Comment by pricecarl** [comment]
Thank you
