### ISSUE TITLE
Support for elasticsearch-5.0.0-alpha2

### ISSUE THREAD

**Issue by topres** [lmenezes/elasticsearch-kopf#359]
Hello there.

How is the kopf support for ES 5? 

I'm currently in the startup phase of a large project, planned to go live this december so we are considering just starting up with ES 5 now, but I'd hate to get started without kopf.

**Comment by jeesim2** [comment]
Take a look at this issue.
https://github.com/lmenezes/elasticsearch-kopf/issues/341

**Comment by lmenezes** [comment]
@jeesim2 thanks for replying :)
