### ISSUE TITLE
Enhancement: reindex capability

### ISSUE THREAD

**Issue by biggiesmallsAG** [lmenezes/elasticsearch-kopf#367]
Would there be any chance of requesting a feature enhancement that enables a given index to be reindexed into a new index?

I know this can be done manually by a scrolling (ive written a python script that does it fine), however, i want to give users of my application the ability to use kopf to monitor their cluster and upon updates to our index mappings, let them choose their old index to reindex into the new index.

Many thanks,

Daniel

**Comment by lmenezes** [comment]
@biggiesmallsAG you do know there is an API for this, right?(https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-reindex.html)

I have yet updated the README, but just so you know, I won't be supporting kopf any longer(as it site plugins won't be supported by ES 5). I'm currently working on a replacement for it(https://github.com/lmenezes/cerebro), but it's still far for complete. On this new app I will make sure to add a section covering the reindex api.

**Comment by biggiesmallsAG** [comment]
wow.. totally overlooked.. excuse the post!
