### ISSUE TITLE
Broken "Analyze by field type" in "Analysis" screen

### ISSUE THREAD

**Issue by vchalmel** [lmenezes/elasticsearch-kopf#369]
Hi,

I have had this strange bug since a few weeks where I can't test analyzers field by field anymore.
The "analyze by analyzer" block works fine, but if I choose a field in "Analyze by field type" it seems to only have a space tokenization (no stemming, no ellision, no stopwords deletion, nothing...)

```
"ar_sous_titre": {
        "analyzer": "analyse_mots_clefs_combines",
        "type": "string",
        "fields": {
          "search": {
            "similarity": "BM25",
            "analyzer": "analyse_texte_libre",
            "term_vector": "with_positions_offsets",
            "type": "string"
          },
          "raw": {
            "similarity": "BM25",
            "analyzer": "analyse_mots_clefs",
            "term_vector": "with_positions_offsets",
            "type": "string"
          }
        }
      },
```

![resultscomp](https://cloud.githubusercontent.com/assets/12208673/17250001/b50c15da-55a2-11e6-9229-09f21e3ccf5f.png)

**Comment by rchelimil** [comment]
Facing same issue. Some notes based on my analysis:

1.  In Elasticsearch 1.x.x, you can specify the field as:
<type>.<field>.

http://localhost:9200/myindex/_analyze?field=mytype.field1

2. In Elasticsearch 2.x.x, specifying the type doesn't work.

Doesn't work:
http://localhost:9200/myindex/_analyze?field=mytype.field1

Works:
http://localhost:9200/myindex/_analyze?field=field1

**Comment by lmenezes** [comment]
hey all,

I guess what might be happening is that you are using ES 2.X with an older version of kopf. Try updating to the most recent version and things should work fine :)

**Comment by lmenezes** [comment]
I will close this for now, but if you still have an issue after upgrading kopf, please reopen it or create a new one.
