### ISSUE TITLE
does not connect to localhost:9200

### ISSUE THREAD

**Issue by pa3dso** [lmenezes/elasticsearch-kopf#370]
hi
Kopf does not connect to localhost:9200 on ELK 5.0.0.alpha4.
Probably not (yet) supported ? 

tnx Ron

**Comment by lmenezes** [comment]
hey,

I assume you are running kopf either as standalone or directly from the public URL(as ES >= 5.0 won't allow you to install site plugins). 

In this case, you would need to allow CORS on your ES config(check https://github.com/lmenezes/elasticsearch-kopf/issues/358 for example)
