### ISSUE TITLE
unable to install this plugin for elasticsearch 5.0.0alpha4

### ISSUE THREAD

**Issue by mrunalgosar** [lmenezes/elasticsearch-kopf#371]
Hi Team..I've updated my elasticsearch to 5.0.0alpha4 version. I wanted to use this really helpful kopf plugin to monitor performance and other metrics. But i am unable to install. while trying to install this plugin using command ./elasticsearch-plugin install file:///<absolute path to kopf plugin> it throws me error stating 

> ERROR: `elasticsearch` directory is missing in the plugin zip

Can someone assist with this

**Comment by Nefelim4ag** [comment]
ES 5.0 don't support plugins.
You can run standalone kopf and then connect to cluster

**Comment by lmenezes** [comment]
hey all.

ES 5.0 won't support site plugins anymore, so you can no longer install site plugins on it.

You can still run kopf locally though, as explained https://github.com/lmenezes/elasticsearch-kopf#installation
