### ISSUE TITLE
Kopf and reverse proxy

### ISSUE THREAD

**Issue by alfmatos** [lmenezes/elasticsearch-kopf#373]
Hi @lmenezes. I've been trying to setup kopf behind a reverse proxy (nginx). I've read through https://github.com/lmenezes/elasticsearch-kopf#kopf-behind-a-reverse-proxy and I've got it to work by reverse proxying both Kopf and ES.

However, this forces me to expose the entire ES api. Is there a way to just proxy Kopf but not ES i.e. forcing Kopf to connect to the server it's on? Both Kopf and Elastic are running on the same (aws) server. I've got the same Kibana setup, and it works fine:

```
location /kibana/ {
  proxy_pass http://localhost:5601;
  rewrite ^/kibana/(.*)$ /$1 break;
  proxy_set_header Host $host;

  auth_basic "Authentication Required";
  auth_basic_user_file htpasswd;
}
```

**Comment by UrielRicardo** [comment]
@lmenezes respond please

**Comment by up-town-down** [comment]
You could run kopf as a standalone in apache on a different port?

I do this and actually use apache as the reverse proxy.

The problem I think you'll have is kopf is just a simple (no offence intended) web app so whomever is running it will still need to be able to see the es api from their browser too, unlike kibana which runs as a server in it's own right and connects to elasticsearch directly so you only need to expose 5601

**Comment by alfmatos** [comment]
@up-town-down you're right. Kopf is standalone, so this will never possible AFAIK. And it seems that kopf is being replaced with cerebro anyway, so we should just close this.
