### ISSUE TITLE
Sending Request Data in REST

### ISSUE THREAD

**Issue by sundarv85** [lmenezes/elasticsearch-kopf#376]
Hello,

Using Sense, one can do a GET with a particular query, such as

```
GET /_search
{
  "query": {
    "bool": {
      "should": [
        {
          "term": {
            "status": {
              "value": "urgent",
              "boost": 2.0 
            }
          }
        },
        {
          "term": {
            "status": "normal" 
          }
        }
      ]
    }
  }
}
```

How to do this in Kopf REST. I see [issue 12](https://github.com/lmenezes/elasticsearch-kopf/issues/12) that REST GET, will not take any data.

**Comment by robison** [comment]
You can use POST instead of GET for this request. According to most current interpretations of RFC2616, GET requests must encode any request data in the Request-URI, and not the body.

**Comment by lmenezes** [comment]
@sundarv85 hey
even though ES does support GET requests with a body, I thought it actually made more sense to disregard the body in a GET request(this way, you don't have to have a valid JSON if you just want to execute a simple _search for example), as ES also allows you to do the same using POST.
