### ISSUE TITLE
display request body on request history

### ISSUE THREAD

**Issue by lmenezes** [lmenezes/elasticsearch-kopf#44]
maybe a tooltip or on click

**Comment by hellboy81** [comment]
Where can I get request history?

**Comment by lmenezes** [comment]
You can get the history for rest requests here. For the body, is actually just a tooltip :)
![screenshot 2015-04-15 14 30 25](https://cloud.githubusercontent.com/assets/750074/7158605/0df66910-e37c-11e4-8f83-552d6b909d6d.png)
