### ISSUE TITLE
Move Shard API

### ISSUE THREAD

**Issue by matthiasfeist** [lmenezes/elasticsearch-kopf#88]
Enhancement Idea: Provide a point&click interface for the shard move API

**Comment by pires** [comment]
+1

**Comment by german23** [comment]
+1

**Comment by Jacketbg** [comment]
This could be very useful for those, who want to manually balance their clusters, e.g. with different hardware where shard distribution isn't even.

**Comment by angad** [comment]
+1 
would definitely love this feature.

**Comment by a-lustin-parc** [comment]
+1

**Comment by up-town-down** [comment]
:+1:
